ENV_NAME = 'AIDONODE_NAME'
ENV_DATA_IN = 'AIDONODE_DATA_IN'
ENV_DATA_OUT = 'AIDONODE_DATA_OUT'
ENV_META_IN = 'AIDONODE_META_IN'
ENV_META_OUT = 'AIDONODE_META_OUT'
ENV_TRANSLATE = 'AIDONODE_TRANSLATE'
ENV_ENCODING = 'AIDONODE_ENCODING'
ENV_CONFIG = 'AIDONODE_CONFIG'
ENV_ENCODING_JSON = 'json'
ENV_ENCODING_CBOR = 'cbor'
ENV_ENCODING_VALID = [ENV_ENCODING_JSON, ENV_ENCODING_CBOR]
KNOWN = [ENV_DATA_IN, ENV_DATA_OUT, ENV_CONFIG, ENV_META_IN, ENV_META_OUT, ENV_NAME, ENV_TRANSLATE, ENV_ENCODING]


TOPIC_ABORTED = 'aborted'

FIELD_DATA = 'data'
FIELD_TOPIC = 'topic'
FIELD_TIMING = 'timing'
FIELD_COMPAT = 'compat'
CUR_PROTOCOL = 'aido2'
