# Generated by Django 2.1.7 on 2019-03-22 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("db_log", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="logrecord",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        )
    ]
