language: python

python:
  - 2.7
  - 3.4
  - 3.6

env:
  - DJANGO=Django==1.4.22 
  - DJANGO=Django==1.5.12 
  - DJANGO=Django==1.6.11 
  - DJANGO=Django==1.7.11 
  - DJANGO=Django==1.8.19 
  - DJANGO=Django==1.10.8 
  - DJANGO=Django==1.11.20
  - DJANGO=Django==2.0.13
  - DJANGO=Django==2.1.7  

install:
  - pip install -q $DJANGO

script:
  - PYTHONPATH=$PYTHONPATH:$PWD django-admin.py test adminrestrict --settings=adminrestrict.test_settings

matrix:
    exclude:
        - python: 3.4
          env: DJANGO=Django==1.4.22
        - python: 2.7
          env: DJANGO=Django==2.0.13
        - python: 2.7
          env: DJANGO=Django==2.1.7
        - python: 3.4
          env: DJANGO=Django==2.1.7            
        - python: 3.6
          env: DJANGO=Django==1.4.22
        - python: 3.6
          env: DJANGO=Django==1.5.12
        - python: 3.6
          env: DJANGO=Django==1.6.11
        - python: 3.6
          env: DJANGO=Django==1.7.11
        - python: 3.6          
          env: DJANGO=Django==1.8.19
        - python: 3.6
          env: DJANGO=Django==1.10.8

