
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-03-28T13:51:06-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "54dc0d04d61d9d4ec5b9b3227d26352c301e1eb4",
 "version": "9.1.0b4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
