language: python
dist: xenial

stages:
- baseline
- name: test
  if: repo = pytest-dev/execnet AND tag IS NOT present
- name: deploy
  if: repo = pytest-dev/execnet AND tag IS present

python:
  - '3.7'

jobs:
  include:
    - stage: baseline
      env: TOXENV=docs
      python: '3.6'
    - env: TOXENV=py27
      python: '2.7'
    - env: TOXENV=py37
      python: '3.7'

    - stage: test
      env: TOXENV=py34
      python: '3.4'
    - env: TOXENV=py35
      python: '3.5'
    - env: TOXENV=py36
      python: '3.6'
    - env: TOXENV=pypy
      python: 'pypy2.7-6.0'
    - env: TOXENV=pypy3
      python: 'pypy3.5-6.0'

    - stage: deploy
      python: '3.7'
      install: pip install -U setuptools setuptools_scm
      script: skip
      deploy:
        provider: pypi
        user: nicoddemus
        distributions: sdist bdist_wheel
        skip_upload_docs: true
        password:
          secure: "gnnagE3aOIHwv+Wonhn4+Ge3biuC8pOCN+aKIOko4ZOWgZlTBZjNSP/PFdhOmQp1sYHsm98GLubF5D5aEmKYQQOkiUn5PLMjyBjijN5qF5wwKK22MR73MCw+zVXt/o5K0uFiXPFTXzRlT2VrD86tjjGIOUQqpXBvm9X+8wu1nL8OkzurWRDzeY8Sv1XopOh6v0PD85fxu6pkFv4iVvNTUytIqTLU4LJTNFdfuWMQvr1JMHgtQUsCdT4CvSPsvu4WGAsYMyNAQFtNJwxqukkPySgVv5vTIdHfnCMURm6vjv9oprO5t3O6fDJS3K/EWxmz5+3CfRBJ20OdDUM62DKsVbjg2rSjuwiafgFKcs+Ob20CalvF4ZOwddQGz3I8n0I0zJarGhEmr/c9XXY31LH/Y3FaghUUYOq4Hfh8+mEZgE7MGyvRjD8zA2Cq8cfOivqg9dM7HQniZSybSCkF47pF+qwRPzYkC9dm8IHi24v1/hA8d7uuXel44dauJiGJqvQ7qN0Bh4ZEuE1EVju+v8NwlTk6C93ShzIRhKUZVx1GgoI/KorRgIlRbd6I24xo2kKtXw2mb5+dnbsL2ip/ungw+saTZsXSWICY/L0Nv+WHWl7DskwSSdl/iKJaztv/7975wXSxLEG+K6xweufx5N6eTh9A1Sa7YLBDOEpTC4lkq0A="
        on:
          tags: true
          repo: pytest-dev/execnet
  allow_failures:
  - env: TOXENV=pypy
    python: 'pypy2.7-6.0'
  - env: TOXENV=pypy3
    python: 'pypy3.5-6.0'


matrix:
  include:
    - env: TOXENV=docs
      python: '3.6'
  allow_failures:
    - python: 'pypy'

install:
  - pip install -U pip
  - pip install -U setuptools setuptools_scm tox

script:
  - tox

notifications:
  irc:
    channels:
      - "chat.freenode.net#pylib"
    on_success: change
    on_failure: change
    skip_join: true
