[tool.poetry]
name = "zeitig"
version = "0.4.1"
description = "time tracker and reporter"
authors = ["Oliver Berger <diefans@gmail.com>"]
license = "Apache-2.0"
homepage = "https://github.com/diefans/zeitig"
repository = "https://github.com/diefans/zeitig"
keywords = "time tracker"
readme = "README.rst"

[tool.poetry.dependencies]
python = "^3.6"
pendulum = "*"
dateparser = "*"
click = "*"
colorama = "*"
crayons = "*"
jinja2 = "*"
qtoml = "^0.2.4"

[tool.poetry.dev-dependencies]
pytest = "*"
pytest-cache = "*"
pytest-randomly = "*"
pytest-cov = "*"
pytest-watch = "*"
pytest-mock = "^1.10"
mock = "^2.0"
pylava = "*"
pylava-pylint = "*"
pycodestyle = "*"
pydocstyle = "*"
radon = "*"
pdbpp = "*"
isort = {version = "^4.3",extras = ["pyproject"]}

[tool.poetry.scripts]
z = "zeitig.scripts:run"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
