
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-03-26T23:07:37-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "3759520e9fee4958a2ce8ca3309f43fc5fdc1b0d",
 "version": "2.2.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
