
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-04-02T20:45:44+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "3d85c4741427684abdabda4bbf280b9daee6ea4f",
 "version": "0.0.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
