
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-03-26T19:23:26+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "408b9c7072fc33af1503fc79aeb31b01292f8b03",
 "version": "0.1.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
