# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/orsinium/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup

import os.path

readme = ''
here = os.path.abspath(os.path.dirname(__file__))
with open(os.path.join(here, 'README.rst'), encoding='utf-8') as stream:
    readme = stream.read()

setup(
    long_description=readme,
    name='dephell_markers',
    version='0.2.1',
    description='Work with environment markers (PEP-496)',
    python_requires='>=3.5',
    author='orsinium',
    packages=[
        'dephell_markers', 'dephell_markers._marker',
        'dephell_markers._operation'
    ],
    package_data={},
    install_requires=['attrs', 'dephell-specifier', 'packaging'],
)
