[tool.poetry]
name = "pupy"
version = "2.4.9"
description = "pretty useful python"
authors = ["jessekrubin <jessekrubin@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^2.7 || ^3.5"

[tool.poetry.dev-dependencies]
pytest = "^4.2"
pytest-cov = "^2.6"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
python = "~2.7 || ^3.2"  # Compatible python versions must be declared here
