
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-03-28T18:02:51-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "3d2538dce83da8053b9909b9c3bb6aab4c855028",
 "version": "1.8.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
