# Generated by Django 2.1.7 on 2019-03-27 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LogRecord",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("funcname", models.CharField(max_length=255)),
                ("modulename", models.CharField(max_length=255)),
                ("username", models.CharField(max_length=255)),
                ("logger", models.CharField(max_length=255)),
                ("level", models.IntegerField()),
                ("trace", models.CharField(max_length=1024)),
                ("msg", models.CharField(max_length=1024)),
            ],
            options={
                "verbose_name": "LogRecord",
                "verbose_name_plural": "LogRecords",
                "ordering": ("id", "-created_at"),
            },
        )
    ]
