[tool.poetry]
name = "harmonator"
version = "0.1.2"
description = "Harmontown Downloader"
authors = ["Chris Read <centurix@gmail.com>"]
readme = "README.rst"
repository = "https://github.com/Centurix/harmonator"
homepage = "https://github.com/Centurix/harmonator"
classifiers = [
    "Development Status :: 2 - Pre-Alpha",
    "Intended Audience :: Developers",
    "Natural Language :: English",
    "Operating System :: POSIX :: Linux",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.6",
    "Programming Language :: Python :: 3.7",
    "Topic :: Multimedia :: Video",
    "Topic :: Utilities"
]

[tool.poetry.dependencies]
python = "^3.6"
click = "^7.0"

[tool.poetry.dev-dependencies]
black = {version = "^18.3-alpha.0",allows-prereleases = true}
pycodestyle = "^2.5"
coverage = "^4.5"
codacy-coverage = "^1.3"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
