from distutils.core import setup
setup(
  name = 'bbrc-bx',
  install_requires=['coverage>=4.5',
      'nose>=1.3',
      'requests>=2.21',
      'six>=1.10',
      'lxml>=4.3',
      'nibabel>=2.3',
      'pydicom>=1.2',
      'numpy>=1.16',
      'pandas>=0.24',
      'xlrd>=1.2',
      'xlutils>=2.0',
      'xlwt>=1.3',
      'tqdm>=4.31'],
  scripts=['bin/bx'],
  version = '0.0.3.4',
  description = 'BarcelonaBeta + XNAT = bx',
  author = 'Greg Operto',
  author_email = 'goperto@barcelonabeta.org',
  url = 'https://gitlab.com/xgrg/bx',
  download_url = 'https://gitlab.com/xgrg/bx/-/archive/v0.0.3.4/bx-v0.0.3.4.tar.gz',
  classifiers = ['Intended Audience :: Science/Research',
      'Intended Audience :: Developers',
      'Topic :: Scientific/Engineering',
      'Operating System :: Unix',
      'Programming Language :: Python :: 3.7' ]
)
