# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from grpc_api_client.grpc.sample import api_pb2 as grpc__api__client_dot_grpc_dot_sample_dot_api__pb2


class APITestStub(object):
  """APITest represents the test gRPC server
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.BoolTest = channel.unary_unary(
        '/api.APITest/BoolTest',
        request_serializer=grpc__api__client_dot_grpc_dot_sample_dot_api__pb2.BoolTestReq.SerializeToString,
        response_deserializer=grpc__api__client_dot_grpc_dot_sample_dot_api__pb2.BoolTestResp.FromString,
        )
    self.StringTest = channel.unary_unary(
        '/api.APITest/StringTest',
        request_serializer=grpc__api__client_dot_grpc_dot_sample_dot_api__pb2.StringTestReq.SerializeToString,
        response_deserializer=grpc__api__client_dot_grpc_dot_sample_dot_api__pb2.StringTestResp.FromString,
        )
    self.Int32Test = channel.unary_unary(
        '/api.APITest/Int32Test',
        request_serializer=grpc__api__client_dot_grpc_dot_sample_dot_api__pb2.Int32TestReq.SerializeToString,
        response_deserializer=grpc__api__client_dot_grpc_dot_sample_dot_api__pb2.Int32TestResp.FromString,
        )
    self.Int64Test = channel.unary_unary(
        '/api.APITest/Int64Test',
        request_serializer=grpc__api__client_dot_grpc_dot_sample_dot_api__pb2.Int64TestReq.SerializeToString,
        response_deserializer=grpc__api__client_dot_grpc_dot_sample_dot_api__pb2.Int64TestResp.FromString,
        )
    self.Uint32Test = channel.unary_unary(
        '/api.APITest/Uint32Test',
        request_serializer=grpc__api__client_dot_grpc_dot_sample_dot_api__pb2.Uint32TestReq.SerializeToString,
        response_deserializer=grpc__api__client_dot_grpc_dot_sample_dot_api__pb2.Uint32TestResp.FromString,
        )
    self.Uint64Test = channel.unary_unary(
        '/api.APITest/Uint64Test',
        request_serializer=grpc__api__client_dot_grpc_dot_sample_dot_api__pb2.Uint64TestReq.SerializeToString,
        response_deserializer=grpc__api__client_dot_grpc_dot_sample_dot_api__pb2.Uint64TestResp.FromString,
        )
    self.BytesTest = channel.unary_unary(
        '/api.APITest/BytesTest',
        request_serializer=grpc__api__client_dot_grpc_dot_sample_dot_api__pb2.BytesTestReq.SerializeToString,
        response_deserializer=grpc__api__client_dot_grpc_dot_sample_dot_api__pb2.BytesTestResp.FromString,
        )


class APITestServicer(object):
  """APITest represents the test gRPC server
  """

  def BoolTest(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def StringTest(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Int32Test(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Int64Test(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Uint32Test(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Uint64Test(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def BytesTest(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_APITestServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'BoolTest': grpc.unary_unary_rpc_method_handler(
          servicer.BoolTest,
          request_deserializer=grpc__api__client_dot_grpc_dot_sample_dot_api__pb2.BoolTestReq.FromString,
          response_serializer=grpc__api__client_dot_grpc_dot_sample_dot_api__pb2.BoolTestResp.SerializeToString,
      ),
      'StringTest': grpc.unary_unary_rpc_method_handler(
          servicer.StringTest,
          request_deserializer=grpc__api__client_dot_grpc_dot_sample_dot_api__pb2.StringTestReq.FromString,
          response_serializer=grpc__api__client_dot_grpc_dot_sample_dot_api__pb2.StringTestResp.SerializeToString,
      ),
      'Int32Test': grpc.unary_unary_rpc_method_handler(
          servicer.Int32Test,
          request_deserializer=grpc__api__client_dot_grpc_dot_sample_dot_api__pb2.Int32TestReq.FromString,
          response_serializer=grpc__api__client_dot_grpc_dot_sample_dot_api__pb2.Int32TestResp.SerializeToString,
      ),
      'Int64Test': grpc.unary_unary_rpc_method_handler(
          servicer.Int64Test,
          request_deserializer=grpc__api__client_dot_grpc_dot_sample_dot_api__pb2.Int64TestReq.FromString,
          response_serializer=grpc__api__client_dot_grpc_dot_sample_dot_api__pb2.Int64TestResp.SerializeToString,
      ),
      'Uint32Test': grpc.unary_unary_rpc_method_handler(
          servicer.Uint32Test,
          request_deserializer=grpc__api__client_dot_grpc_dot_sample_dot_api__pb2.Uint32TestReq.FromString,
          response_serializer=grpc__api__client_dot_grpc_dot_sample_dot_api__pb2.Uint32TestResp.SerializeToString,
      ),
      'Uint64Test': grpc.unary_unary_rpc_method_handler(
          servicer.Uint64Test,
          request_deserializer=grpc__api__client_dot_grpc_dot_sample_dot_api__pb2.Uint64TestReq.FromString,
          response_serializer=grpc__api__client_dot_grpc_dot_sample_dot_api__pb2.Uint64TestResp.SerializeToString,
      ),
      'BytesTest': grpc.unary_unary_rpc_method_handler(
          servicer.BytesTest,
          request_deserializer=grpc__api__client_dot_grpc_dot_sample_dot_api__pb2.BytesTestReq.FromString,
          response_serializer=grpc__api__client_dot_grpc_dot_sample_dot_api__pb2.BytesTestResp.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'api.APITest', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
