# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpc_api_client/grpc/sample/api.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='grpc_api_client/grpc/sample/api.proto',
  package='api',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n%grpc_api_client/grpc/sample/api.proto\x12\x03\x61pi\",\n\x0b\x42oolTestReq\x12\r\n\x05value\x18\x01 \x01(\x08\x12\x0e\n\x06values\x18\x02 \x03(\x08\"-\n\x0c\x42oolTestResp\x12\r\n\x05value\x18\x01 \x01(\x08\x12\x0e\n\x06values\x18\x02 \x03(\x08\".\n\rStringTestReq\x12\r\n\x05value\x18\x01 \x01(\t\x12\x0e\n\x06values\x18\x02 \x03(\x08\"/\n\x0eStringTestResp\x12\r\n\x05value\x18\x01 \x01(\t\x12\x0e\n\x06values\x18\x02 \x03(\t\"-\n\x0cInt32TestReq\x12\r\n\x05value\x18\x01 \x01(\x05\x12\x0e\n\x06values\x18\x02 \x03(\t\".\n\rInt32TestResp\x12\r\n\x05value\x18\x01 \x01(\x05\x12\x0e\n\x06values\x18\x02 \x03(\x05\"-\n\x0cInt64TestReq\x12\r\n\x05value\x18\x01 \x01(\x03\x12\x0e\n\x06values\x18\x02 \x03(\x05\".\n\rInt64TestResp\x12\r\n\x05value\x18\x01 \x01(\x03\x12\x0e\n\x06values\x18\x02 \x03(\x03\".\n\rUint32TestReq\x12\r\n\x05value\x18\x01 \x01(\r\x12\x0e\n\x06values\x18\x02 \x03(\x03\"/\n\x0eUint32TestResp\x12\r\n\x05value\x18\x01 \x01(\r\x12\x0e\n\x06values\x18\x02 \x03(\r\".\n\rUint64TestReq\x12\r\n\x05value\x18\x01 \x01(\x04\x12\x0e\n\x06values\x18\x02 \x03(\x04\"/\n\x0eUint64TestResp\x12\r\n\x05value\x18\x01 \x01(\x04\x12\x0e\n\x06values\x18\x02 \x03(\x04\"-\n\x0c\x42ytesTestReq\x12\r\n\x05value\x18\x01 \x01(\x0c\x12\x0e\n\x06values\x18\x02 \x03(\x0c\".\n\rBytesTestResp\x12\r\n\x05value\x18\x01 \x01(\x0c\x12\x0e\n\x06values\x18\x02 \x03(\x0c\x32\x89\x03\n\x07\x41PITest\x12\x31\n\x08\x42oolTest\x12\x10.api.BoolTestReq\x1a\x11.api.BoolTestResp\"\x00\x12\x37\n\nStringTest\x12\x12.api.StringTestReq\x1a\x13.api.StringTestResp\"\x00\x12\x34\n\tInt32Test\x12\x11.api.Int32TestReq\x1a\x12.api.Int32TestResp\"\x00\x12\x34\n\tInt64Test\x12\x11.api.Int64TestReq\x1a\x12.api.Int64TestResp\"\x00\x12\x37\n\nUint32Test\x12\x12.api.Uint32TestReq\x1a\x13.api.Uint32TestResp\"\x00\x12\x37\n\nUint64Test\x12\x12.api.Uint64TestReq\x1a\x13.api.Uint64TestResp\"\x00\x12\x34\n\tBytesTest\x12\x11.api.BytesTestReq\x1a\x12.api.BytesTestResp\"\x00\x62\x06proto3')
)




_BOOLTESTREQ = _descriptor.Descriptor(
  name='BoolTestReq',
  full_name='api.BoolTestReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='api.BoolTestReq.value', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='values', full_name='api.BoolTestReq.values', index=1,
      number=2, type=8, cpp_type=7, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=46,
  serialized_end=90,
)


_BOOLTESTRESP = _descriptor.Descriptor(
  name='BoolTestResp',
  full_name='api.BoolTestResp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='api.BoolTestResp.value', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='values', full_name='api.BoolTestResp.values', index=1,
      number=2, type=8, cpp_type=7, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=92,
  serialized_end=137,
)


_STRINGTESTREQ = _descriptor.Descriptor(
  name='StringTestReq',
  full_name='api.StringTestReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='api.StringTestReq.value', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='values', full_name='api.StringTestReq.values', index=1,
      number=2, type=8, cpp_type=7, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=139,
  serialized_end=185,
)


_STRINGTESTRESP = _descriptor.Descriptor(
  name='StringTestResp',
  full_name='api.StringTestResp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='api.StringTestResp.value', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='values', full_name='api.StringTestResp.values', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=187,
  serialized_end=234,
)


_INT32TESTREQ = _descriptor.Descriptor(
  name='Int32TestReq',
  full_name='api.Int32TestReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='api.Int32TestReq.value', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='values', full_name='api.Int32TestReq.values', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=236,
  serialized_end=281,
)


_INT32TESTRESP = _descriptor.Descriptor(
  name='Int32TestResp',
  full_name='api.Int32TestResp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='api.Int32TestResp.value', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='values', full_name='api.Int32TestResp.values', index=1,
      number=2, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=283,
  serialized_end=329,
)


_INT64TESTREQ = _descriptor.Descriptor(
  name='Int64TestReq',
  full_name='api.Int64TestReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='api.Int64TestReq.value', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='values', full_name='api.Int64TestReq.values', index=1,
      number=2, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=331,
  serialized_end=376,
)


_INT64TESTRESP = _descriptor.Descriptor(
  name='Int64TestResp',
  full_name='api.Int64TestResp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='api.Int64TestResp.value', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='values', full_name='api.Int64TestResp.values', index=1,
      number=2, type=3, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=378,
  serialized_end=424,
)


_UINT32TESTREQ = _descriptor.Descriptor(
  name='Uint32TestReq',
  full_name='api.Uint32TestReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='api.Uint32TestReq.value', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='values', full_name='api.Uint32TestReq.values', index=1,
      number=2, type=3, cpp_type=2, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=426,
  serialized_end=472,
)


_UINT32TESTRESP = _descriptor.Descriptor(
  name='Uint32TestResp',
  full_name='api.Uint32TestResp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='api.Uint32TestResp.value', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='values', full_name='api.Uint32TestResp.values', index=1,
      number=2, type=13, cpp_type=3, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=474,
  serialized_end=521,
)


_UINT64TESTREQ = _descriptor.Descriptor(
  name='Uint64TestReq',
  full_name='api.Uint64TestReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='api.Uint64TestReq.value', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='values', full_name='api.Uint64TestReq.values', index=1,
      number=2, type=4, cpp_type=4, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=523,
  serialized_end=569,
)


_UINT64TESTRESP = _descriptor.Descriptor(
  name='Uint64TestResp',
  full_name='api.Uint64TestResp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='api.Uint64TestResp.value', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='values', full_name='api.Uint64TestResp.values', index=1,
      number=2, type=4, cpp_type=4, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=571,
  serialized_end=618,
)


_BYTESTESTREQ = _descriptor.Descriptor(
  name='BytesTestReq',
  full_name='api.BytesTestReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='api.BytesTestReq.value', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='values', full_name='api.BytesTestReq.values', index=1,
      number=2, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=620,
  serialized_end=665,
)


_BYTESTESTRESP = _descriptor.Descriptor(
  name='BytesTestResp',
  full_name='api.BytesTestResp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='value', full_name='api.BytesTestResp.value', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='values', full_name='api.BytesTestResp.values', index=1,
      number=2, type=12, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=667,
  serialized_end=713,
)

DESCRIPTOR.message_types_by_name['BoolTestReq'] = _BOOLTESTREQ
DESCRIPTOR.message_types_by_name['BoolTestResp'] = _BOOLTESTRESP
DESCRIPTOR.message_types_by_name['StringTestReq'] = _STRINGTESTREQ
DESCRIPTOR.message_types_by_name['StringTestResp'] = _STRINGTESTRESP
DESCRIPTOR.message_types_by_name['Int32TestReq'] = _INT32TESTREQ
DESCRIPTOR.message_types_by_name['Int32TestResp'] = _INT32TESTRESP
DESCRIPTOR.message_types_by_name['Int64TestReq'] = _INT64TESTREQ
DESCRIPTOR.message_types_by_name['Int64TestResp'] = _INT64TESTRESP
DESCRIPTOR.message_types_by_name['Uint32TestReq'] = _UINT32TESTREQ
DESCRIPTOR.message_types_by_name['Uint32TestResp'] = _UINT32TESTRESP
DESCRIPTOR.message_types_by_name['Uint64TestReq'] = _UINT64TESTREQ
DESCRIPTOR.message_types_by_name['Uint64TestResp'] = _UINT64TESTRESP
DESCRIPTOR.message_types_by_name['BytesTestReq'] = _BYTESTESTREQ
DESCRIPTOR.message_types_by_name['BytesTestResp'] = _BYTESTESTRESP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

BoolTestReq = _reflection.GeneratedProtocolMessageType('BoolTestReq', (_message.Message,), dict(
  DESCRIPTOR = _BOOLTESTREQ,
  __module__ = 'grpc_api_client.grpc.sample.api_pb2'
  # @@protoc_insertion_point(class_scope:api.BoolTestReq)
  ))
_sym_db.RegisterMessage(BoolTestReq)

BoolTestResp = _reflection.GeneratedProtocolMessageType('BoolTestResp', (_message.Message,), dict(
  DESCRIPTOR = _BOOLTESTRESP,
  __module__ = 'grpc_api_client.grpc.sample.api_pb2'
  # @@protoc_insertion_point(class_scope:api.BoolTestResp)
  ))
_sym_db.RegisterMessage(BoolTestResp)

StringTestReq = _reflection.GeneratedProtocolMessageType('StringTestReq', (_message.Message,), dict(
  DESCRIPTOR = _STRINGTESTREQ,
  __module__ = 'grpc_api_client.grpc.sample.api_pb2'
  # @@protoc_insertion_point(class_scope:api.StringTestReq)
  ))
_sym_db.RegisterMessage(StringTestReq)

StringTestResp = _reflection.GeneratedProtocolMessageType('StringTestResp', (_message.Message,), dict(
  DESCRIPTOR = _STRINGTESTRESP,
  __module__ = 'grpc_api_client.grpc.sample.api_pb2'
  # @@protoc_insertion_point(class_scope:api.StringTestResp)
  ))
_sym_db.RegisterMessage(StringTestResp)

Int32TestReq = _reflection.GeneratedProtocolMessageType('Int32TestReq', (_message.Message,), dict(
  DESCRIPTOR = _INT32TESTREQ,
  __module__ = 'grpc_api_client.grpc.sample.api_pb2'
  # @@protoc_insertion_point(class_scope:api.Int32TestReq)
  ))
_sym_db.RegisterMessage(Int32TestReq)

Int32TestResp = _reflection.GeneratedProtocolMessageType('Int32TestResp', (_message.Message,), dict(
  DESCRIPTOR = _INT32TESTRESP,
  __module__ = 'grpc_api_client.grpc.sample.api_pb2'
  # @@protoc_insertion_point(class_scope:api.Int32TestResp)
  ))
_sym_db.RegisterMessage(Int32TestResp)

Int64TestReq = _reflection.GeneratedProtocolMessageType('Int64TestReq', (_message.Message,), dict(
  DESCRIPTOR = _INT64TESTREQ,
  __module__ = 'grpc_api_client.grpc.sample.api_pb2'
  # @@protoc_insertion_point(class_scope:api.Int64TestReq)
  ))
_sym_db.RegisterMessage(Int64TestReq)

Int64TestResp = _reflection.GeneratedProtocolMessageType('Int64TestResp', (_message.Message,), dict(
  DESCRIPTOR = _INT64TESTRESP,
  __module__ = 'grpc_api_client.grpc.sample.api_pb2'
  # @@protoc_insertion_point(class_scope:api.Int64TestResp)
  ))
_sym_db.RegisterMessage(Int64TestResp)

Uint32TestReq = _reflection.GeneratedProtocolMessageType('Uint32TestReq', (_message.Message,), dict(
  DESCRIPTOR = _UINT32TESTREQ,
  __module__ = 'grpc_api_client.grpc.sample.api_pb2'
  # @@protoc_insertion_point(class_scope:api.Uint32TestReq)
  ))
_sym_db.RegisterMessage(Uint32TestReq)

Uint32TestResp = _reflection.GeneratedProtocolMessageType('Uint32TestResp', (_message.Message,), dict(
  DESCRIPTOR = _UINT32TESTRESP,
  __module__ = 'grpc_api_client.grpc.sample.api_pb2'
  # @@protoc_insertion_point(class_scope:api.Uint32TestResp)
  ))
_sym_db.RegisterMessage(Uint32TestResp)

Uint64TestReq = _reflection.GeneratedProtocolMessageType('Uint64TestReq', (_message.Message,), dict(
  DESCRIPTOR = _UINT64TESTREQ,
  __module__ = 'grpc_api_client.grpc.sample.api_pb2'
  # @@protoc_insertion_point(class_scope:api.Uint64TestReq)
  ))
_sym_db.RegisterMessage(Uint64TestReq)

Uint64TestResp = _reflection.GeneratedProtocolMessageType('Uint64TestResp', (_message.Message,), dict(
  DESCRIPTOR = _UINT64TESTRESP,
  __module__ = 'grpc_api_client.grpc.sample.api_pb2'
  # @@protoc_insertion_point(class_scope:api.Uint64TestResp)
  ))
_sym_db.RegisterMessage(Uint64TestResp)

BytesTestReq = _reflection.GeneratedProtocolMessageType('BytesTestReq', (_message.Message,), dict(
  DESCRIPTOR = _BYTESTESTREQ,
  __module__ = 'grpc_api_client.grpc.sample.api_pb2'
  # @@protoc_insertion_point(class_scope:api.BytesTestReq)
  ))
_sym_db.RegisterMessage(BytesTestReq)

BytesTestResp = _reflection.GeneratedProtocolMessageType('BytesTestResp', (_message.Message,), dict(
  DESCRIPTOR = _BYTESTESTRESP,
  __module__ = 'grpc_api_client.grpc.sample.api_pb2'
  # @@protoc_insertion_point(class_scope:api.BytesTestResp)
  ))
_sym_db.RegisterMessage(BytesTestResp)



_APITEST = _descriptor.ServiceDescriptor(
  name='APITest',
  full_name='api.APITest',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=716,
  serialized_end=1109,
  methods=[
  _descriptor.MethodDescriptor(
    name='BoolTest',
    full_name='api.APITest.BoolTest',
    index=0,
    containing_service=None,
    input_type=_BOOLTESTREQ,
    output_type=_BOOLTESTRESP,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='StringTest',
    full_name='api.APITest.StringTest',
    index=1,
    containing_service=None,
    input_type=_STRINGTESTREQ,
    output_type=_STRINGTESTRESP,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Int32Test',
    full_name='api.APITest.Int32Test',
    index=2,
    containing_service=None,
    input_type=_INT32TESTREQ,
    output_type=_INT32TESTRESP,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Int64Test',
    full_name='api.APITest.Int64Test',
    index=3,
    containing_service=None,
    input_type=_INT64TESTREQ,
    output_type=_INT64TESTRESP,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Uint32Test',
    full_name='api.APITest.Uint32Test',
    index=4,
    containing_service=None,
    input_type=_UINT32TESTREQ,
    output_type=_UINT32TESTRESP,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Uint64Test',
    full_name='api.APITest.Uint64Test',
    index=5,
    containing_service=None,
    input_type=_UINT64TESTREQ,
    output_type=_UINT64TESTRESP,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='BytesTest',
    full_name='api.APITest.BytesTest',
    index=6,
    containing_service=None,
    input_type=_BYTESTESTREQ,
    output_type=_BYTESTESTRESP,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_APITEST)

DESCRIPTOR.services_by_name['APITest'] = _APITEST

# @@protoc_insertion_point(module_scope)
