# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class DataPathParameter(Model):
    """DataPathParameter.

    Variables are only populated by the server, and will be ignored when
    sending a request.

    :ivar name:
    :vartype name: str
    :ivar documentation:
    :vartype documentation: str
    :ivar default_value:
    :vartype default_value: ~swagger.models.DataPath
    :ivar is_optional:
    :vartype is_optional: bool
    :ivar data_type_id:
    :vartype data_type_id: str
    """

    _attribute_map = {
        'name': {'key': 'Name', 'type': 'str'},
        'documentation': {'key': 'Documentation', 'type': 'str'},
        'default_value': {'key': 'DefaultValue', 'type': 'DataPath'},
        'is_optional': {'key': 'IsOptional', 'type': 'bool'},
        'data_type_id': {'key': 'DataTypeId', 'type': 'str'},
    }

    def __init__(self, name=None, documentation=None, default_value=None, is_optional=None, data_type_id=None):
        super(DataPathParameter, self).__init__()
        self.name = name
        self.documentation = documentation
        self.default_value = default_value
        self.is_optional = is_optional
        self.data_type_id = data_type_id
