# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class EntityInterface(Model):
    """EntityInterface.

    :param parameters:
    :type parameters: list[~swagger.models.Parameter]
    :param data_path_parameters:
    :type data_path_parameters: list[~swagger.models.DataPathParameter]
    :param ports:
    :type ports: ~swagger.models.NodePortInterface
    :param metadata_parameters:
    :type metadata_parameters: list[~swagger.models.Parameter]
    """

    _attribute_map = {
        'parameters': {'key': 'Parameters', 'type': '[Parameter]'},
        'data_path_parameters': {'key': 'DataPathParameters', 'type': '[DataPathParameter]'},
        'ports': {'key': 'Ports', 'type': 'NodePortInterface'},
        'metadata_parameters': {'key': 'MetadataParameters', 'type': '[Parameter]'},
    }

    def __init__(self, parameters=None, data_path_parameters=None, ports=None, metadata_parameters=None):
        super(EntityInterface, self).__init__()
        self.parameters = parameters
        self.data_path_parameters = data_path_parameters
        self.ports = ports
        self.metadata_parameters = metadata_parameters
