
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-04-12T09:39:35+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "5d893ef51c1cc95cb9eaff0702827f8f02ea26fa",
 "version": "0.2.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
