from datetime import datetime
from typing import Tuple

def format_filename(episode: int, episode_date: datetime) -> str: ...

def parse_filename(episode_filename: str) -> Tuple: ...

def test(a: str) -> str: ...
