# Generated by Django 2.1.7 on 2019-03-31 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('latch', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LatchSetup',
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'UserProfile', 'verbose_name_plural': 'UserProfiles'},
        ),
    ]
