#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

extras_require = \
{'dev': ['flake8'], 'doc': ['sphinx'], 'test': ['pytest', 'pytest-cov']}

setup(name='prybar',
      version='1.0.0',
      description='Create temporary pkg_resources entry points at runtime.',
      author='Hal Blackburn',
      author_email='hwtb2@cam.ac.uk',
      url='https://github.com/h4l/prybar',
      py_modules=['prybar'],
      extras_require=extras_require,
      python_requires='~=3.6',
     )
