
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "11983688fb714211320c14c5bb53fb8349c5e5e8",
 "version": "0.16.0.b3838"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
