
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-04-10T10:17:46-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "dd4f5b85f7e048a96f0cfd21a2be5d11b8fd6995",
 "version": "V1.0.14"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
