
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-04-10T13:01:36-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "4a07120f4e03f4ce3fa5ef0dc96bc899d54aa61e",
 "version": "V1.0.15"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
