# This file was automatically generated by sub\epyqlib\epyqlib\cli\generateversion.py
__version_build_time__ = '2019-03-31T19:38:00.300700'

__version__ = '2019.3.8'
__sha__ = 'd742653424a99de0eb45fd1d2380683ae49e6577'
__revision__ = 'd742653424a99de0eb45fd1d2380683ae49e6577'
