# Generated by Django 2.1.4 on 2019-03-27 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saleboxdjango', '0002_checkoutstore_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='salebox_member_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
