
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-03-28T16:09:09-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "7ae613acaf7db9f67c3354b3625b9130b8ed2097",
 "version": "2019.3.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
