[tool.poetry]
name = "reg-bench"
version = "0.0.3"
description = ""
readme = "README.md"
authors = ["Markus Quade <info@markusqua.de>"]
license = "MIT"
repository = "https://github.com/Ohjeah/regression-benchmarks"

[tool.poetry.dependencies]
python = "^3.7"
numpy = "^1.15"
toolz = "^0.9.0"
pyodesys = "^0.12.4"
scikit-learn = {version = "^0.20.1",extras = ["alldeps"]}
derivative = "^0.1.2"

[tool.poetry.dev-dependencies]
matplotlib = "^3.0"
pytest = "^4.1"

[tool.black]
line-length = 111
py36 = true
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
