
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-04-12T11:16:17-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "1849b1707ffc10ce427f68f6f1cb90529140bc8a",
 "version": "0.14.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
