#!/usr/bin/env python
# setup.py generated by flit for tools that don't yet use PEP 517

from distutils.core import setup

packages = \
['dlive']

package_data = \
{'': ['*']}

setup(name='dlive',
      version='1.0.0',
      description='A Python wrapper for the DLive API.',
      author='Aareon Sullivan',
      author_email='aareon@died-in.space',
      url='https://github.com/Aareon/PyDLive',
      packages=packages,
      package_data=package_data,
     )
