[tool.poetry]
name = "dophon-properties"
version = "0.1.3r7"
description = "dophon properties"
authors = ["CallMeE <ealohu@163.com>"]
url="https://github.com/Ca11MeE/dophon"
license='Apache 2.0'
keywords = ['web', 'framework', 'dophon']

[tool.poetry.dependencies]
python = "^3.6"
PyYaml = "*"

[tool.poetry.dev-dependencies]
pytest = "^3.6"
