
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-03-28T22:45:14+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "59fff3761af07a59f8f1c1682f2be004bdac15f7",
 "version": "0.12.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
