language: python

python:
  - 2.7
  - 3.2
  - 3.3
  - 3.4
  - 3.5
  - pypy

matrix:
  allow_failures:
    - python: 3.3
    - python: 3.4
    - python: 3.5

install:
  - pip install -r requirements.txt

script:
  - nosetests
