container:
  image: python:3.7

pip_cache: &pip_cache
  folder: ~/.cache/pip
  fingerprint_script: echo $PYTHON_VERSION && cat Pipfile.lock
  populate_script: pip install black mypy pylint pytest

setup_cache_task:
  pip_cache: *pip_cache

test_task:
  depends_on: setup_cache
  pip_cache: *pip_cache
  intall_script: pip install pytest
  test_script: python -m pytest

typecheck_task:
  depends_on: setup_cache
  pip_cache: *pip_cache
  intall_script: pip install mypy
  test_script: python -m mypy dataclass_structor

formatter_task:
  depends_on: setup_cache
  pip_cache: *pip_cache
  intall_script: pip install black
  test_script: python -m black --diff --check dataclass_structor tests

linter_task:
  depends_on: setup_cache
  pip_cache: *pip_cache
  intall_script: pip install pylint
  test_script: pylint --rcfile=.pylintrc dataclass_structor tests
