[build-system]
requires = ["flit"]
build-backend = "flit.buildapi"

[tool.flit.metadata]
module = "dataclass_structor"
author = "Douglas Anderson"
author-email = "hockeybuggy@gmail.com"
home-page = "https://github.com/hockeybuggy/dataclass_structor"
description-file = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3.7",
]

[tool.flit.metadata.urls]
Documentation = "https://dataclass-structor.readthedocs.io"

