- project:
    templates:
      - check-requirements
      - horizon-nodejs4-jobs
      - horizon-nodejs10-jobs
      - openstack-lower-constraints-jobs-horizon
      - openstack-python-jobs-horizon
      - openstack-python36-jobs-horizon
      - openstack-python37-jobs-horizon
      - publish-openstack-docs-pti
      - release-notes-jobs-python3
    check:
      jobs:
        - horizon-openstack-tox-python3-django111
    gate:
      jobs:
        - horizon-openstack-tox-python3-django111
