run_id: "20180920_112044" #use with quotes when the name composed of numbers

fastq_dir: /home/labs/bioservices/pmrefael/snakemake/input

output_dir: /home/labs/bioservices/pmrefael/snakemake

factors_file: 'pheno_data.csv'

#The file name must to start with creature alias, for example mm10.gtf
gtf: /home/labs/walkerlab/Collaboration/161124_NB501465_0039_AHWJGNBGXY/by_old_pipeline/mm10.genes.3utr.gtf

my_star_index: /shareDB/iGenomes/Mus_musculus/UCSC/mm10/Sequence/STAR_index/

##### Don't change it.
scripts: /apps/RH7U2/scripts/bbcu-python-packages/python27-ve-ngs-snakemake/bin

templates: /apps/RH7U2/scripts/bbcu-python-packages/python27-ve-ngs-snakemake/lib/python2.7/site-packages/ngs-snakemake

python: /apps/RH7U2/scripts/bbcu-python-packages/python27-ve-ngs-snakemake/bin/python

Rscript: /apps/RH7U2/gnu/R/3.4.2/bin/Rscript

R_lib_paths: /apps/RH7U2/scripts/bbcu-R-packages

#For internal using, no need full path because we do module load
cutadapt_exe: cutadapt

fastqc_exe: fastqc

star_exe: STAR

samtools_exe: samtools

ngs_plot_exe: ngs.plot.r

gs_exe: gs

htseq_count_exe: htseq-count

max_threads_num: 100
#####