[tool.poetry]
name = "dictstack"
version = "0.1.1"
description = "A multi-level dictionary that can overlay values in layers."
authors = ["Lee Braiden <leebraid@gmail.com>"]
license = "MIT"
repository = "https://github.com/lee-b/dictstack"

[tool.poetry.dependencies]
python = ">2.7"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
