[tool.poetry]
name = "shopify-requests"
version = "0.4.0"
description = "Wrapper around the Shopify API using requests."
authors = ["Paul Robertson <t.paulrobertson@gmail.com>"]
license = "MIT"
readme = "README.md"
repository = "https://gitlab.com/perobertson/shopify-requests"
documentation = "https://shopify-requests.readthedocs.io/"
keywords = [
  "shopify",
  "requests"
]

[tool.poetry.dependencies]
python = "~2.7 || ^3.5"
requests = "^2.21"

[tool.poetry.dev-dependencies]
flake8 = "^3.6"
flake8-docstrings = "^1.3"
flake8-import-order = "^0.18.1"
future = "^0.17.1"
ipython = "^5.0"
pep8-naming = "^0.8.2"
pytest = "^4.0"
pytest-cov = "^2.6"
requests_mock = "^1.5"

[build-system]
requires = ["poetry>=0.12,!=0.12.12"]
build-backend = "poetry.masonry.api"
