
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-04-03T18:45:51+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "9b48edeca618b4c7fd9643d42c3f5457779f39bd",
 "version": "v3.1.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
