language: python
python:
- '3.4'
- '3.5'
- '3.6'
install:
- pip install .
- pip install coveralls
script: coverage run --source=posttroll setup.py test
after_success: coveralls
deploy:
  provider: pypi
  user: Martin.Raspaud
  password:
    secure: dole4qxvcCpRrxtrRZucGp5jeCdI3sGZUclge2e7YrlasTa8eVszXg4MTmW4XiV8CMQs5PymyfNKPRxaaBKm8U2BGjrwFWNcXH/pyaWlnXdyQ1Tm3Owf/RDz9oCYULLQXcKgu3UljUHYz+9NbfE67sfDLJiFsi3VHRjKut+eUwo=
  on:
    tags: true
    repo: pytroll/posttroll
