
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-03-29T15:12:02-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "67c8e0f3b6501e5e8fd8e484a01132b6e32b33e5",
 "version": "0.0.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
