
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-04-06T13:26:33-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "8f40542c6f5184af8233dfc0cd2111e5d31a48d9",
 "version": "0.4.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
