# coding: utf-8

"""
    ApproveAPISwagger

    The simple API to request a user's approval on anything via email + sms.  # noqa: E501

    OpenAPI spec version: 1.0.1
    Contact: dev@approveapi.com
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import approveapi_swagger
from approveapi_swagger.api.approve_api import ApproveApi  # noqa: E501
from approveapi_swagger.rest import ApiException


class TestApproveApi(unittest.TestCase):
    """ApproveApi unit test stubs"""

    def setUp(self):
        self.api = approveapi_swagger.api.approve_api.ApproveApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_prompt(self):
        """Test case for create_prompt

        Sending a prompt  # noqa: E501
        """
        pass

    def test_get_prompt(self):
        """Test case for get_prompt

        Retrieve a prompt  # noqa: E501
        """
        pass

    def test_get_prompt_status(self):
        """Test case for get_prompt_status

        Check prompt status  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
