# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ava_engine/ava/feature_classification.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ava_engine.ava import engine_core_pb2 as ava__engine_dot_ava_dot_engine__core__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ava_engine/ava/feature_classification.proto',
  package='ava_engine',
  syntax='proto3',
  serialized_pb=_b('\n+ava_engine/ava/feature_classification.proto\x12\nava_engine\x1a ava_engine/ava/engine_core.proto\"E\n\x1e\x43lassificationFeatureArguments\x12\x12\n\nis_enabled\x18\x01 \x01(\x08\x12\x0f\n\x07\x63lasses\x18\x02 \x03(\t\"w\n\x0f\x43lassifyRequest\x12%\n\x06images\x18\x01 \x03(\x0b\x32\x15.ava_engine.ImageItem\x12\x0f\n\x07\x63lasses\x18\x02 \x03(\t\x12,\n\x0bpersistence\x18\x03 \x01(\x0e\x32\x17.ava_engine.Persistence\"C\n\x10\x43lassifyResponse\x12/\n\x06images\x18\x01 \x03(\x0b\x32\x1f.ava_engine.ClassifyImageResult\"\xbb\x01\n\x13\x43lassifyImageResult\x12\x10\n\x08image_id\x18\x01 \x01(\t\x12\x0f\n\x07\x66\x65\x65\x64_id\x18\x02 \x01(\t\x12\x11\n\tcustom_id\x18\x03 \x01(\t\x12+\n\x07results\x18\x04 \x03(\x0b\x32\x1a.ava_engine.ClassifyResult\x12\x32\n\x0f\x65xclusion_zones\x18\x05 \x03(\x0b\x32\x19.ava_engine.ExclusionZone\x12\r\n\x05is_ir\x18\x06 \x01(\x08\"E\n\x0e\x43lassifyResult\x12\r\n\x05\x63lass\x18\x01 \x01(\t\x12\x12\n\nconfidence\x18\x02 \x01(\x02\x12\x10\n\x08model_id\x18\x03 \x01(\tB#\n!com.imageintelligence.engine.grpcb\x06proto3')
  ,
  dependencies=[ava__engine_dot_ava_dot_engine__core__pb2.DESCRIPTOR,])




_CLASSIFICATIONFEATUREARGUMENTS = _descriptor.Descriptor(
  name='ClassificationFeatureArguments',
  full_name='ava_engine.ClassificationFeatureArguments',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='is_enabled', full_name='ava_engine.ClassificationFeatureArguments.is_enabled', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='classes', full_name='ava_engine.ClassificationFeatureArguments.classes', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=93,
  serialized_end=162,
)


_CLASSIFYREQUEST = _descriptor.Descriptor(
  name='ClassifyRequest',
  full_name='ava_engine.ClassifyRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='images', full_name='ava_engine.ClassifyRequest.images', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='classes', full_name='ava_engine.ClassifyRequest.classes', index=1,
      number=2, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='persistence', full_name='ava_engine.ClassifyRequest.persistence', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=164,
  serialized_end=283,
)


_CLASSIFYRESPONSE = _descriptor.Descriptor(
  name='ClassifyResponse',
  full_name='ava_engine.ClassifyResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='images', full_name='ava_engine.ClassifyResponse.images', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=285,
  serialized_end=352,
)


_CLASSIFYIMAGERESULT = _descriptor.Descriptor(
  name='ClassifyImageResult',
  full_name='ava_engine.ClassifyImageResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='image_id', full_name='ava_engine.ClassifyImageResult.image_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='feed_id', full_name='ava_engine.ClassifyImageResult.feed_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='custom_id', full_name='ava_engine.ClassifyImageResult.custom_id', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='results', full_name='ava_engine.ClassifyImageResult.results', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='exclusion_zones', full_name='ava_engine.ClassifyImageResult.exclusion_zones', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='is_ir', full_name='ava_engine.ClassifyImageResult.is_ir', index=5,
      number=6, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=355,
  serialized_end=542,
)


_CLASSIFYRESULT = _descriptor.Descriptor(
  name='ClassifyResult',
  full_name='ava_engine.ClassifyResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='class', full_name='ava_engine.ClassifyResult.class', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='confidence', full_name='ava_engine.ClassifyResult.confidence', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='model_id', full_name='ava_engine.ClassifyResult.model_id', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=544,
  serialized_end=613,
)

_CLASSIFYREQUEST.fields_by_name['images'].message_type = ava__engine_dot_ava_dot_engine__core__pb2._IMAGEITEM
_CLASSIFYREQUEST.fields_by_name['persistence'].enum_type = ava__engine_dot_ava_dot_engine__core__pb2._PERSISTENCE
_CLASSIFYRESPONSE.fields_by_name['images'].message_type = _CLASSIFYIMAGERESULT
_CLASSIFYIMAGERESULT.fields_by_name['results'].message_type = _CLASSIFYRESULT
_CLASSIFYIMAGERESULT.fields_by_name['exclusion_zones'].message_type = ava__engine_dot_ava_dot_engine__core__pb2._EXCLUSIONZONE
DESCRIPTOR.message_types_by_name['ClassificationFeatureArguments'] = _CLASSIFICATIONFEATUREARGUMENTS
DESCRIPTOR.message_types_by_name['ClassifyRequest'] = _CLASSIFYREQUEST
DESCRIPTOR.message_types_by_name['ClassifyResponse'] = _CLASSIFYRESPONSE
DESCRIPTOR.message_types_by_name['ClassifyImageResult'] = _CLASSIFYIMAGERESULT
DESCRIPTOR.message_types_by_name['ClassifyResult'] = _CLASSIFYRESULT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ClassificationFeatureArguments = _reflection.GeneratedProtocolMessageType('ClassificationFeatureArguments', (_message.Message,), dict(
  DESCRIPTOR = _CLASSIFICATIONFEATUREARGUMENTS,
  __module__ = 'ava_engine.ava.feature_classification_pb2'
  # @@protoc_insertion_point(class_scope:ava_engine.ClassificationFeatureArguments)
  ))
_sym_db.RegisterMessage(ClassificationFeatureArguments)

ClassifyRequest = _reflection.GeneratedProtocolMessageType('ClassifyRequest', (_message.Message,), dict(
  DESCRIPTOR = _CLASSIFYREQUEST,
  __module__ = 'ava_engine.ava.feature_classification_pb2'
  # @@protoc_insertion_point(class_scope:ava_engine.ClassifyRequest)
  ))
_sym_db.RegisterMessage(ClassifyRequest)

ClassifyResponse = _reflection.GeneratedProtocolMessageType('ClassifyResponse', (_message.Message,), dict(
  DESCRIPTOR = _CLASSIFYRESPONSE,
  __module__ = 'ava_engine.ava.feature_classification_pb2'
  # @@protoc_insertion_point(class_scope:ava_engine.ClassifyResponse)
  ))
_sym_db.RegisterMessage(ClassifyResponse)

ClassifyImageResult = _reflection.GeneratedProtocolMessageType('ClassifyImageResult', (_message.Message,), dict(
  DESCRIPTOR = _CLASSIFYIMAGERESULT,
  __module__ = 'ava_engine.ava.feature_classification_pb2'
  # @@protoc_insertion_point(class_scope:ava_engine.ClassifyImageResult)
  ))
_sym_db.RegisterMessage(ClassifyImageResult)

ClassifyResult = _reflection.GeneratedProtocolMessageType('ClassifyResult', (_message.Message,), dict(
  DESCRIPTOR = _CLASSIFYRESULT,
  __module__ = 'ava_engine.ava.feature_classification_pb2'
  # @@protoc_insertion_point(class_scope:ava_engine.ClassifyResult)
  ))
_sym_db.RegisterMessage(ClassifyResult)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n!com.imageintelligence.engine.grpc'))
# @@protoc_insertion_point(module_scope)
