stages:
  - py35
  - py36
  - py37
test-py3.5:
  image: python:3.5
  stage: py35
  script:
  - pip3 install -r requirements.txt
  - python3.5 -m pytest --cov rpg tests
test-py3.6:
  image: python:3.6
  stage: py36
  script:
  - pip3 install -r requirements.txt
  - python3.6 -m pytest --cov rpg tests
test-py3.7:
  image: python:3.7
  stage: py37
  script:
  - pip3 install -r requirements.txt
  - python3.7 -m pytest --cov rpg tests
