# Generated by Django 2.0.5 on 2018-09-12 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bots', '0005_auto_20180701_1514'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hidden', models.BooleanField(default=False)),
                ('command', models.CharField(db_index=True, max_length=64, unique=True)),
                ('title', models.CharField(db_index=True, max_length=128, unique=True)),
                ('text', models.TextField(max_length=4096)),
                ('bot', models.ForeignKey(limit_choices_to={'plugin_name': 'telebaka_faq'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bots.TelegramBot')),
            ],
        ),
    ]
