# Generated by Django 2.0.5 on 2018-09-15 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telebaka_faq', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faqsection',
            name='text',
            field=models.TextField(),
        ),
    ]
