# Generated by Django 2.0.5 on 2018-09-15 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telebaka_faq', '0002_auto_20180915_1423'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faqsection',
            options={'ordering': ['weight']},
        ),
        migrations.AddField(
            model_name='faqsection',
            name='weight',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
