- project:
    templates:
      - tempest-plugin-jobs
      - check-requirements
    check:
      jobs:
        - blazar-devstack-dsvm
    gate:
      queue: blazar
      jobs:
        - blazar-devstack-dsvm
