[tool.poetry]
name = "aws-codedeploy-watcher"
version = "0.1.4"
description = "Observe AWS Codedeploy deployments live"
authors = ["Daniel Miranda <danielkza2@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^2.7 || ^3.4"
boto3 = "^1.9"
botocore = "^1.12"
pendulum = "^2.0"

[tool.poetry.dev-dependencies]

[tool.poetry.scripts]
aws-codedeploy-watcher = 'aws_codedeploy_watcher:main'

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
