
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "8b75ead8f97dd4d05d8d5659b4c9f5dbd6584a1c",
 "version": "2114"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
