
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-04-05T20:33:24+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "8ea585f4eae81ca7fd787d8f1d2d644577d34e78",
 "version": "2.0rc2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
