
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-04-03T16:11:10-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "3e92aea11acded14074041b7da3104f4af702463",
 "version": "0.1.0a3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
