# Generated by Django 2.1.7 on 2019-03-23 02:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [("db_log", "0002_auto_20190322_2139")]

    operations = [
        migrations.AlterModelOptions(
            name="logrecord",
            options={
                "ordering": ("-created_at",),
                "verbose_name": "LogRecord",
                "verbose_name_plural": "LogRecords",
            },
        ),
        migrations.AddField(
            model_name="logrecord",
            name="funcname",
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="logrecord",
            name="modulename",
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="logrecord",
            name="username",
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
