[tool.poetry]
name = "commons-1c"
version = "3.1.1"
description = "Commons for 1C:Enterprise"
authors = ["Cujoko <cujoko@gmail.com>"]
license = "MIT"
homepage = "https://github.com/Cujoko/commons-1c"
repository = "https://github.com/Cujoko/commons-1c"
documentation = "https://github.com/Cujoko/commons-1c"
keywords = ["1c", "commons"]
classifiers=[
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Natural Language :: Russian",
    "Programming Language :: Python :: 3.7",
    "Topic :: Software Development",
    "Topic :: Utilities"
]

[tool.poetry.dependencies]
python = "^3.7"
appdirs = "^1.4"
cjk-commons = "^3.3"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
