
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-04-03T11:52:04-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "7a4eafc229f83784f4c63d639aee554f9a6b1ca0",
 "version": "v2.2.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
