
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-04-07T20:07:37-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "199ca4823acec98d003ca5c153221b64f96cb582",
 "version": "v0.6.9"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
