# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dynagatewaytypes/action.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from dynagatewaytypes import general_types_pb2 as dynagatewaytypes_dot_general__types__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='dynagatewaytypes/action.proto',
  package='dynagatewaytypes',
  syntax='proto3',
  serialized_options=_b('\n!com.dynactionize.dynagatewaytypesZ$go.dynactionize.com/dynagatewaytypes\210\001\001'),
  serialized_pb=_b('\n\x1d\x64ynagatewaytypes/action.proto\x12\x10\x64ynagatewaytypes\x1a$dynagatewaytypes/general_types.proto\"\x1f\n\x0f\x43reateActionReq\x12\x0c\n\x04name\x18\x02 \x01(\t\"8\n\x0cGetActionReq\x12\x0c\n\x02id\x18\x02 \x01(\tH\x00\x12\x0e\n\x04name\x18\x03 \x01(\tH\x00\x42\n\n\x08selector\"+\n\x0fRenameActionReq\x12\n\n\x02id\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\"L\n\x0f\x44\x65leteActionReq\x12\x0c\n\x02id\x18\x02 \x01(\tH\x00\x12\x0e\n\x04name\x18\x03 \x01(\tH\x00\x12\x0f\n\x07\x63\x61scade\x18\x04 \x01(\x08\x42\n\n\x08selector\"\xa1\x01\n\x0f\x43reateActionRes\x12\x14\n\x0cstream_index\x18\x01 \x01(\x03\x12\x35\n\x05\x65rror\x18\x02 \x01(\x0b\x32$.dynagatewaytypes.StreamElementErrorH\x00\x12\x35\n\x04item\x18\x03 \x01(\x0b\x32%.dynagatewaytypes.CreateActionResItemH\x00\x42\n\n\x08response\"!\n\x13\x43reateActionResItem\x12\n\n\x02id\x18\x01 \x01(\t\"\x98\x01\n\x0cGetActionRes\x12\x14\n\x0cstream_index\x18\x01 \x01(\x03\x12\x35\n\x05\x65rror\x18\x02 \x01(\x0b\x32$.dynagatewaytypes.StreamElementErrorH\x00\x12/\n\x04item\x18\x03 \x01(\x0b\x32\x1f.dynagatewaytypes.ActionResItemH\x00\x42\n\n\x08response\")\n\rActionResItem\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t2\xda\x03\n\rActionService\x12R\n\x06\x43reate\x12!.dynagatewaytypes.CreateActionReq\x1a!.dynagatewaytypes.CreateActionRes(\x01\x30\x01\x12I\n\x03Get\x12\x1e.dynagatewaytypes.GetActionReq\x1a\x1e.dynagatewaytypes.GetActionRes(\x01\x30\x01\x12?\n\x05\x43ount\x12\x1a.dynagatewaytypes.EmptyReq\x1a\x1a.dynagatewaytypes.CountRes\x12\x43\n\x04Show\x12\x19.dynagatewaytypes.ShowReq\x1a\x1e.dynagatewaytypes.GetActionRes0\x01\x12Q\n\x06Rename\x12!.dynagatewaytypes.RenameActionReq\x1a .dynagatewaytypes.EmptyStreamRes(\x01\x30\x01\x12Q\n\x06\x44\x65lete\x12!.dynagatewaytypes.DeleteActionReq\x1a .dynagatewaytypes.EmptyStreamRes(\x01\x30\x01\x42L\n!com.dynactionize.dynagatewaytypesZ$go.dynactionize.com/dynagatewaytypes\x88\x01\x01\x62\x06proto3')
  ,
  dependencies=[dynagatewaytypes_dot_general__types__pb2.DESCRIPTOR,])




_CREATEACTIONREQ = _descriptor.Descriptor(
  name='CreateActionReq',
  full_name='dynagatewaytypes.CreateActionReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='dynagatewaytypes.CreateActionReq.name', index=0,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=89,
  serialized_end=120,
)


_GETACTIONREQ = _descriptor.Descriptor(
  name='GetActionReq',
  full_name='dynagatewaytypes.GetActionReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='dynagatewaytypes.GetActionReq.id', index=0,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='dynagatewaytypes.GetActionReq.name', index=1,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='selector', full_name='dynagatewaytypes.GetActionReq.selector',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=122,
  serialized_end=178,
)


_RENAMEACTIONREQ = _descriptor.Descriptor(
  name='RenameActionReq',
  full_name='dynagatewaytypes.RenameActionReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='dynagatewaytypes.RenameActionReq.id', index=0,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='dynagatewaytypes.RenameActionReq.name', index=1,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=180,
  serialized_end=223,
)


_DELETEACTIONREQ = _descriptor.Descriptor(
  name='DeleteActionReq',
  full_name='dynagatewaytypes.DeleteActionReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='dynagatewaytypes.DeleteActionReq.id', index=0,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='dynagatewaytypes.DeleteActionReq.name', index=1,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cascade', full_name='dynagatewaytypes.DeleteActionReq.cascade', index=2,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='selector', full_name='dynagatewaytypes.DeleteActionReq.selector',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=225,
  serialized_end=301,
)


_CREATEACTIONRES = _descriptor.Descriptor(
  name='CreateActionRes',
  full_name='dynagatewaytypes.CreateActionRes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='stream_index', full_name='dynagatewaytypes.CreateActionRes.stream_index', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='error', full_name='dynagatewaytypes.CreateActionRes.error', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='item', full_name='dynagatewaytypes.CreateActionRes.item', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='response', full_name='dynagatewaytypes.CreateActionRes.response',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=304,
  serialized_end=465,
)


_CREATEACTIONRESITEM = _descriptor.Descriptor(
  name='CreateActionResItem',
  full_name='dynagatewaytypes.CreateActionResItem',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='dynagatewaytypes.CreateActionResItem.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=467,
  serialized_end=500,
)


_GETACTIONRES = _descriptor.Descriptor(
  name='GetActionRes',
  full_name='dynagatewaytypes.GetActionRes',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='stream_index', full_name='dynagatewaytypes.GetActionRes.stream_index', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='error', full_name='dynagatewaytypes.GetActionRes.error', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='item', full_name='dynagatewaytypes.GetActionRes.item', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='response', full_name='dynagatewaytypes.GetActionRes.response',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=503,
  serialized_end=655,
)


_ACTIONRESITEM = _descriptor.Descriptor(
  name='ActionResItem',
  full_name='dynagatewaytypes.ActionResItem',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='dynagatewaytypes.ActionResItem.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='dynagatewaytypes.ActionResItem.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=657,
  serialized_end=698,
)

_GETACTIONREQ.oneofs_by_name['selector'].fields.append(
  _GETACTIONREQ.fields_by_name['id'])
_GETACTIONREQ.fields_by_name['id'].containing_oneof = _GETACTIONREQ.oneofs_by_name['selector']
_GETACTIONREQ.oneofs_by_name['selector'].fields.append(
  _GETACTIONREQ.fields_by_name['name'])
_GETACTIONREQ.fields_by_name['name'].containing_oneof = _GETACTIONREQ.oneofs_by_name['selector']
_DELETEACTIONREQ.oneofs_by_name['selector'].fields.append(
  _DELETEACTIONREQ.fields_by_name['id'])
_DELETEACTIONREQ.fields_by_name['id'].containing_oneof = _DELETEACTIONREQ.oneofs_by_name['selector']
_DELETEACTIONREQ.oneofs_by_name['selector'].fields.append(
  _DELETEACTIONREQ.fields_by_name['name'])
_DELETEACTIONREQ.fields_by_name['name'].containing_oneof = _DELETEACTIONREQ.oneofs_by_name['selector']
_CREATEACTIONRES.fields_by_name['error'].message_type = dynagatewaytypes_dot_general__types__pb2._STREAMELEMENTERROR
_CREATEACTIONRES.fields_by_name['item'].message_type = _CREATEACTIONRESITEM
_CREATEACTIONRES.oneofs_by_name['response'].fields.append(
  _CREATEACTIONRES.fields_by_name['error'])
_CREATEACTIONRES.fields_by_name['error'].containing_oneof = _CREATEACTIONRES.oneofs_by_name['response']
_CREATEACTIONRES.oneofs_by_name['response'].fields.append(
  _CREATEACTIONRES.fields_by_name['item'])
_CREATEACTIONRES.fields_by_name['item'].containing_oneof = _CREATEACTIONRES.oneofs_by_name['response']
_GETACTIONRES.fields_by_name['error'].message_type = dynagatewaytypes_dot_general__types__pb2._STREAMELEMENTERROR
_GETACTIONRES.fields_by_name['item'].message_type = _ACTIONRESITEM
_GETACTIONRES.oneofs_by_name['response'].fields.append(
  _GETACTIONRES.fields_by_name['error'])
_GETACTIONRES.fields_by_name['error'].containing_oneof = _GETACTIONRES.oneofs_by_name['response']
_GETACTIONRES.oneofs_by_name['response'].fields.append(
  _GETACTIONRES.fields_by_name['item'])
_GETACTIONRES.fields_by_name['item'].containing_oneof = _GETACTIONRES.oneofs_by_name['response']
DESCRIPTOR.message_types_by_name['CreateActionReq'] = _CREATEACTIONREQ
DESCRIPTOR.message_types_by_name['GetActionReq'] = _GETACTIONREQ
DESCRIPTOR.message_types_by_name['RenameActionReq'] = _RENAMEACTIONREQ
DESCRIPTOR.message_types_by_name['DeleteActionReq'] = _DELETEACTIONREQ
DESCRIPTOR.message_types_by_name['CreateActionRes'] = _CREATEACTIONRES
DESCRIPTOR.message_types_by_name['CreateActionResItem'] = _CREATEACTIONRESITEM
DESCRIPTOR.message_types_by_name['GetActionRes'] = _GETACTIONRES
DESCRIPTOR.message_types_by_name['ActionResItem'] = _ACTIONRESITEM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CreateActionReq = _reflection.GeneratedProtocolMessageType('CreateActionReq', (_message.Message,), dict(
  DESCRIPTOR = _CREATEACTIONREQ,
  __module__ = 'dynagatewaytypes.action_pb2'
  # @@protoc_insertion_point(class_scope:dynagatewaytypes.CreateActionReq)
  ))
_sym_db.RegisterMessage(CreateActionReq)

GetActionReq = _reflection.GeneratedProtocolMessageType('GetActionReq', (_message.Message,), dict(
  DESCRIPTOR = _GETACTIONREQ,
  __module__ = 'dynagatewaytypes.action_pb2'
  # @@protoc_insertion_point(class_scope:dynagatewaytypes.GetActionReq)
  ))
_sym_db.RegisterMessage(GetActionReq)

RenameActionReq = _reflection.GeneratedProtocolMessageType('RenameActionReq', (_message.Message,), dict(
  DESCRIPTOR = _RENAMEACTIONREQ,
  __module__ = 'dynagatewaytypes.action_pb2'
  # @@protoc_insertion_point(class_scope:dynagatewaytypes.RenameActionReq)
  ))
_sym_db.RegisterMessage(RenameActionReq)

DeleteActionReq = _reflection.GeneratedProtocolMessageType('DeleteActionReq', (_message.Message,), dict(
  DESCRIPTOR = _DELETEACTIONREQ,
  __module__ = 'dynagatewaytypes.action_pb2'
  # @@protoc_insertion_point(class_scope:dynagatewaytypes.DeleteActionReq)
  ))
_sym_db.RegisterMessage(DeleteActionReq)

CreateActionRes = _reflection.GeneratedProtocolMessageType('CreateActionRes', (_message.Message,), dict(
  DESCRIPTOR = _CREATEACTIONRES,
  __module__ = 'dynagatewaytypes.action_pb2'
  # @@protoc_insertion_point(class_scope:dynagatewaytypes.CreateActionRes)
  ))
_sym_db.RegisterMessage(CreateActionRes)

CreateActionResItem = _reflection.GeneratedProtocolMessageType('CreateActionResItem', (_message.Message,), dict(
  DESCRIPTOR = _CREATEACTIONRESITEM,
  __module__ = 'dynagatewaytypes.action_pb2'
  # @@protoc_insertion_point(class_scope:dynagatewaytypes.CreateActionResItem)
  ))
_sym_db.RegisterMessage(CreateActionResItem)

GetActionRes = _reflection.GeneratedProtocolMessageType('GetActionRes', (_message.Message,), dict(
  DESCRIPTOR = _GETACTIONRES,
  __module__ = 'dynagatewaytypes.action_pb2'
  # @@protoc_insertion_point(class_scope:dynagatewaytypes.GetActionRes)
  ))
_sym_db.RegisterMessage(GetActionRes)

ActionResItem = _reflection.GeneratedProtocolMessageType('ActionResItem', (_message.Message,), dict(
  DESCRIPTOR = _ACTIONRESITEM,
  __module__ = 'dynagatewaytypes.action_pb2'
  # @@protoc_insertion_point(class_scope:dynagatewaytypes.ActionResItem)
  ))
_sym_db.RegisterMessage(ActionResItem)


DESCRIPTOR._options = None

_ACTIONSERVICE = _descriptor.ServiceDescriptor(
  name='ActionService',
  full_name='dynagatewaytypes.ActionService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=701,
  serialized_end=1175,
  methods=[
  _descriptor.MethodDescriptor(
    name='Create',
    full_name='dynagatewaytypes.ActionService.Create',
    index=0,
    containing_service=None,
    input_type=_CREATEACTIONREQ,
    output_type=_CREATEACTIONRES,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Get',
    full_name='dynagatewaytypes.ActionService.Get',
    index=1,
    containing_service=None,
    input_type=_GETACTIONREQ,
    output_type=_GETACTIONRES,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Count',
    full_name='dynagatewaytypes.ActionService.Count',
    index=2,
    containing_service=None,
    input_type=dynagatewaytypes_dot_general__types__pb2._EMPTYREQ,
    output_type=dynagatewaytypes_dot_general__types__pb2._COUNTRES,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Show',
    full_name='dynagatewaytypes.ActionService.Show',
    index=3,
    containing_service=None,
    input_type=dynagatewaytypes_dot_general__types__pb2._SHOWREQ,
    output_type=_GETACTIONRES,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Rename',
    full_name='dynagatewaytypes.ActionService.Rename',
    index=4,
    containing_service=None,
    input_type=_RENAMEACTIONREQ,
    output_type=dynagatewaytypes_dot_general__types__pb2._EMPTYSTREAMRES,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='Delete',
    full_name='dynagatewaytypes.ActionService.Delete',
    index=5,
    containing_service=None,
    input_type=_DELETEACTIONREQ,
    output_type=dynagatewaytypes_dot_general__types__pb2._EMPTYSTREAMRES,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_ACTIONSERVICE)

DESCRIPTOR.services_by_name['ActionService'] = _ACTIONSERVICE

# @@protoc_insertion_point(module_scope)
