# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from dynagatewaytypes import networkquery_pb2 as dynagatewaytypes_dot_networkquery__pb2


class NetworkServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.CreateContext = channel.unary_unary(
        '/dynagatewaytypes.NetworkService/CreateContext',
        request_serializer=dynagatewaytypes_dot_networkquery__pb2.CreateNetworkContextReq.SerializeToString,
        response_deserializer=dynagatewaytypes_dot_networkquery__pb2.NetworkContextRes.FromString,
        )
    self.SetGlobalOverlaySettings = channel.unary_unary(
        '/dynagatewaytypes.NetworkService/SetGlobalOverlaySettings',
        request_serializer=dynagatewaytypes_dot_networkquery__pb2.NetworkGlobalOverlaySettingsReq.SerializeToString,
        response_deserializer=dynagatewaytypes_dot_networkquery__pb2.NetworkContextRes.FromString,
        )
    self.AddLabelMappings = channel.stream_unary(
        '/dynagatewaytypes.NetworkService/AddLabelMappings',
        request_serializer=dynagatewaytypes_dot_networkquery__pb2.AddNetworkLabelMappingReq.SerializeToString,
        response_deserializer=dynagatewaytypes_dot_networkquery__pb2.NetworkContextRes.FromString,
        )
    self.SetActionOverlaySettings = channel.stream_unary(
        '/dynagatewaytypes.NetworkService/SetActionOverlaySettings',
        request_serializer=dynagatewaytypes_dot_networkquery__pb2.SetNetworkActionOverlaySettingsReq.SerializeToString,
        response_deserializer=dynagatewaytypes_dot_networkquery__pb2.NetworkContextRes.FromString,
        )
    self.OverrideInternalLinking = channel.stream_unary(
        '/dynagatewaytypes.NetworkService/OverrideInternalLinking',
        request_serializer=dynagatewaytypes_dot_networkquery__pb2.OverrideNetworkInternalLinkingReq.SerializeToString,
        response_deserializer=dynagatewaytypes_dot_networkquery__pb2.NetworkContextRes.FromString,
        )
    self.OverrideElementOverlaySettings = channel.stream_unary(
        '/dynagatewaytypes.NetworkService/OverrideElementOverlaySettings',
        request_serializer=dynagatewaytypes_dot_networkquery__pb2.OverrideNetworkElementOverlaySettingsReq.SerializeToString,
        response_deserializer=dynagatewaytypes_dot_networkquery__pb2.NetworkContextRes.FromString,
        )
    self.Query = channel.unary_unary(
        '/dynagatewaytypes.NetworkService/Query',
        request_serializer=dynagatewaytypes_dot_networkquery__pb2.NetworkQueryReq.SerializeToString,
        response_deserializer=dynagatewaytypes_dot_networkquery__pb2.NetworkQueryRes.FromString,
        )
    self.FetchNodes = channel.unary_stream(
        '/dynagatewaytypes.NetworkService/FetchNodes',
        request_serializer=dynagatewaytypes_dot_networkquery__pb2.NetworkNodesFetchReq.SerializeToString,
        response_deserializer=dynagatewaytypes_dot_networkquery__pb2.NetworkNodesFetchRes.FromString,
        )
    self.FetchLinks = channel.unary_stream(
        '/dynagatewaytypes.NetworkService/FetchLinks',
        request_serializer=dynagatewaytypes_dot_networkquery__pb2.NetworkLinksFetchReq.SerializeToString,
        response_deserializer=dynagatewaytypes_dot_networkquery__pb2.NetworkLinksFetchRes.FromString,
        )


class NetworkServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def CreateContext(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SetGlobalOverlaySettings(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def AddLabelMappings(self, request_iterator, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def SetActionOverlaySettings(self, request_iterator, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def OverrideInternalLinking(self, request_iterator, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def OverrideElementOverlaySettings(self, request_iterator, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def Query(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def FetchNodes(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def FetchLinks(self, request, context):
    """rpc FetchLinksFromNode(NetworkLinksFromNodeFetchReq) returns(stream NetworkLinksFetchRes);
    rpc FetchPathToNode(NetworkPathToNodeFetchReq) returns(stream NetworkLinksFetchRes);
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_NetworkServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'CreateContext': grpc.unary_unary_rpc_method_handler(
          servicer.CreateContext,
          request_deserializer=dynagatewaytypes_dot_networkquery__pb2.CreateNetworkContextReq.FromString,
          response_serializer=dynagatewaytypes_dot_networkquery__pb2.NetworkContextRes.SerializeToString,
      ),
      'SetGlobalOverlaySettings': grpc.unary_unary_rpc_method_handler(
          servicer.SetGlobalOverlaySettings,
          request_deserializer=dynagatewaytypes_dot_networkquery__pb2.NetworkGlobalOverlaySettingsReq.FromString,
          response_serializer=dynagatewaytypes_dot_networkquery__pb2.NetworkContextRes.SerializeToString,
      ),
      'AddLabelMappings': grpc.stream_unary_rpc_method_handler(
          servicer.AddLabelMappings,
          request_deserializer=dynagatewaytypes_dot_networkquery__pb2.AddNetworkLabelMappingReq.FromString,
          response_serializer=dynagatewaytypes_dot_networkquery__pb2.NetworkContextRes.SerializeToString,
      ),
      'SetActionOverlaySettings': grpc.stream_unary_rpc_method_handler(
          servicer.SetActionOverlaySettings,
          request_deserializer=dynagatewaytypes_dot_networkquery__pb2.SetNetworkActionOverlaySettingsReq.FromString,
          response_serializer=dynagatewaytypes_dot_networkquery__pb2.NetworkContextRes.SerializeToString,
      ),
      'OverrideInternalLinking': grpc.stream_unary_rpc_method_handler(
          servicer.OverrideInternalLinking,
          request_deserializer=dynagatewaytypes_dot_networkquery__pb2.OverrideNetworkInternalLinkingReq.FromString,
          response_serializer=dynagatewaytypes_dot_networkquery__pb2.NetworkContextRes.SerializeToString,
      ),
      'OverrideElementOverlaySettings': grpc.stream_unary_rpc_method_handler(
          servicer.OverrideElementOverlaySettings,
          request_deserializer=dynagatewaytypes_dot_networkquery__pb2.OverrideNetworkElementOverlaySettingsReq.FromString,
          response_serializer=dynagatewaytypes_dot_networkquery__pb2.NetworkContextRes.SerializeToString,
      ),
      'Query': grpc.unary_unary_rpc_method_handler(
          servicer.Query,
          request_deserializer=dynagatewaytypes_dot_networkquery__pb2.NetworkQueryReq.FromString,
          response_serializer=dynagatewaytypes_dot_networkquery__pb2.NetworkQueryRes.SerializeToString,
      ),
      'FetchNodes': grpc.unary_stream_rpc_method_handler(
          servicer.FetchNodes,
          request_deserializer=dynagatewaytypes_dot_networkquery__pb2.NetworkNodesFetchReq.FromString,
          response_serializer=dynagatewaytypes_dot_networkquery__pb2.NetworkNodesFetchRes.SerializeToString,
      ),
      'FetchLinks': grpc.unary_stream_rpc_method_handler(
          servicer.FetchLinks,
          request_deserializer=dynagatewaytypes_dot_networkquery__pb2.NetworkLinksFetchReq.FromString,
          response_serializer=dynagatewaytypes_dot_networkquery__pb2.NetworkLinksFetchRes.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'dynagatewaytypes.NetworkService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
