
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-04-01T17:47:23+1100",
 "dirty": false,
 "error": null,
 "full-revisionid": "73213a6622e8dbc7aa4a6a82da847f132d4977c1",
 "version": "v0.1.0.post1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
