# coding: utf-8

"""
    Allegro REST API

    https://developer.allegro.pl/about  # noqa: E501

    OpenAPI spec version: latest
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class CheckoutFormOrderWaybillResponse(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'shipments': 'list[CheckoutFormAddWaybillCreated]'
    }

    attribute_map = {
        'shipments': 'shipments'
    }

    def __init__(self, shipments=None):  # noqa: E501
        """CheckoutFormOrderWaybillResponse - a model defined in OpenAPI"""  # noqa: E501

        self._shipments = None
        self.discriminator = None

        if shipments is not None:
            self.shipments = shipments

    @property
    def shipments(self):
        """Gets the shipments of this CheckoutFormOrderWaybillResponse.  # noqa: E501

        List of parcel tracking numbers currently assigned to the order.  # noqa: E501

        :return: The shipments of this CheckoutFormOrderWaybillResponse.  # noqa: E501
        :rtype: list[CheckoutFormAddWaybillCreated]
        """
        return self._shipments

    @shipments.setter
    def shipments(self, shipments):
        """Sets the shipments of this CheckoutFormOrderWaybillResponse.

        List of parcel tracking numbers currently assigned to the order.  # noqa: E501

        :param shipments: The shipments of this CheckoutFormOrderWaybillResponse.  # noqa: E501
        :type: list[CheckoutFormAddWaybillCreated]
        """

        self._shipments = shipments

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CheckoutFormOrderWaybillResponse):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
