# coding: utf-8

"""
    Allegro REST API

    https://developer.allegro.pl/about  # noqa: E501

    OpenAPI spec version: latest
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class DescribesSuccessCommissionFee(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'fee': 'Fee',
        'name': 'str',
        'type': 'str'
    }

    attribute_map = {
        'fee': 'fee',
        'name': 'name',
        'type': 'type'
    }

    def __init__(self, fee=None, name=None, type=None):  # noqa: E501
        """DescribesSuccessCommissionFee - a model defined in OpenAPI"""  # noqa: E501

        self._fee = None
        self._name = None
        self._type = None
        self.discriminator = None

        self.fee = fee
        self.name = name
        self.type = type

    @property
    def fee(self):
        """Gets the fee of this DescribesSuccessCommissionFee.  # noqa: E501


        :return: The fee of this DescribesSuccessCommissionFee.  # noqa: E501
        :rtype: Fee
        """
        return self._fee

    @fee.setter
    def fee(self, fee):
        """Sets the fee of this DescribesSuccessCommissionFee.


        :param fee: The fee of this DescribesSuccessCommissionFee.  # noqa: E501
        :type: Fee
        """
        if fee is None:
            raise ValueError("Invalid value for `fee`, must not be `None`")  # noqa: E501

        self._fee = fee

    @property
    def name(self):
        """Gets the name of this DescribesSuccessCommissionFee.  # noqa: E501


        :return: The name of this DescribesSuccessCommissionFee.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this DescribesSuccessCommissionFee.


        :param name: The name of this DescribesSuccessCommissionFee.  # noqa: E501
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def type(self):
        """Gets the type of this DescribesSuccessCommissionFee.  # noqa: E501


        :return: The type of this DescribesSuccessCommissionFee.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this DescribesSuccessCommissionFee.


        :param type: The type of this DescribesSuccessCommissionFee.  # noqa: E501
        :type: str
        """
        if type is None:
            raise ValueError("Invalid value for `type`, must not be `None`")  # noqa: E501

        self._type = type

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, DescribesSuccessCommissionFee):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
