language: python

python:
  - "2.7"
  - "3.4"

install:
  - pip install -r requirements.txt
  - pip install -r test-requirements.txt

script: nosetests

deploy:
  provider: pypi
  user: internaphosting
  password:
    secure: nztUy6LTQreUCivL/g+8PFaFkSKPvAEJEe5i/qvfvJky4j6H5gCdnUl3SULRD2xaNztE/kWiT1hs4PqThR8isoay0gB7/8YhVeoMjMHjvi92LXcNu5zsvNpZMq68XKQU8c4nFCwkBtPdu7IumBuow0OmohnLFb0/zTC13U20dZ+F4PMD842e4SgXtXlwjF5OROVi8Djz7CeLxti3O6FytPCaljN3I/a+qtlxbkI+SUXTGTyZNwatoYdt/UI7O+JfvjT79MDTzQhpfB+O1+z4KhYsTcaXrwLGhggA5VKu10ykBBiRqU9neJ1LJvqdxCpjLjKRcohurrRgmRhtBK4v9+M9bKMsqGOmG15YsJrjhXbahvzjx13cpPds6a1Bf1Hs2Ny1l3SjxRKlRyEQKyhufg4td6MzrzfZyNXTbEk601StSbCWV8Mdj3nVdfS3of2yNYIHeSRaioPuJAZrtb/qnN73n6k44UZbw/p6Tk6Tf1wtCqQI+sHAeG2NVaHp6HDxd5Qdg1Zp2XLxE8GnbkCyuFzjxxIMCrUnv1UBo4B+3xj6FMfINOJs6cCHISvvc0icJEmqIhVZwOicd9Dywj71IvdFDZ1xGR5ehR8M7fCqP+UXBVf+SnYTZPcz9cP+fTCBuLpixiFpsX0qPL75dRHb8X0DoOUuVgHky1VKquNay14=
  on:
    tags: true
    python: 3.4
    repo: internap/python-config-probe
