
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-04-09T22:38:47+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "b3a1761977a855c04cbb3ea5879ee5daf5898cbf",
 "version": "0.0.10"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
