[tool.poetry]
name = "all_purpose_dict"
version = "0.1.4"
description = "A dict that works with both hashable and non-hashable keys"
authors = ["Philip Olson <philip.olson@pm.me>"]
license = "WTFNMFPL-1.0"
readme = "README.md"
repository = "https://github.com/olsonpm/py_all-purpose-dict"
include = ["license.txt"]

[tool.poetry.dependencies]
python = "^3.7"
ordered_set = "^3.1"
wrapt = "^1.10"

[tool.poetry.dev-dependencies]
simple_chalk = "^0.1.0"
is_git_repo_clean = "^0.3.4"
toml = "^0.10.0"
tedent = "^0.1.1"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
