# imf = [
#         salpeter     = Salpeter 1955
#         chabrier     = Chabrier 2003
#         ferrini      = Ferrini, Palla & Penco 1998
#         kroupa       = Kroupa 2002 (default)
#         miller_scalo = Miller & Scalo 1979
#         starburst    = Starburst 1999
#         maschberger  = Maschberger 2012
#       ]

# sol_ab = [
#            ag89 = Anders & Grevesse 1989
#            gs98 = Grevesse & Sauval 1998
#            as05 = Asplund et al. 2005
#            as09 = Asplund et al. 2009 (default)
#            he10 = Heger 2010
#          ]

# dtd_sn = [
#            mdvp = DTD from Mannucci, Della Valle, Panagia 2006
#            rlp  = DTD from Ruiz-Lapuente (default)
#          ]

z: 0.02
sol_ab: as09
imf: kroupa
m_max: 40.0
dtd_sn: rlp
