
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-03-30T18:33:42-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "e0d9b41c4345b95dfd1d2f4b69685623f1ed5ad1",
 "version": "v0.1.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
