
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "d4d58056bffbfb748a4af8cd1cd2f4555f2301bf",
 "version": "2.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
