# Generated by Django 2.0.7 on 2018-07-15 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True, verbose_name='Активна?')),
                ('name', models.CharField(max_length=150, verbose_name='Заголовок')),
                ('code', models.TextField(default=None, max_length=5000, verbose_name='Данные')),
            ],
            options={
                'verbose_name': 'Метрика',
                'verbose_name_plural': 'Метрики',
            },
        ),
        migrations.CreateModel(
            name='MetaData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=68, verbose_name='Заголовок')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Опис')),
                ('keywords', models.CharField(blank=True, max_length=255, verbose_name='Ключєві слова')),
                ('author', models.CharField(blank=True, max_length=255, verbose_name='Автор')),
                ('robots', models.CharField(blank=True, choices=[('', '---------'), ('index, follow', 'index, follow'), ('index, nofollow', 'index, nofollow'), ('noindex, nofollow', 'noindex, nofollow'), ('noindex, follow', 'noindex, follow')], max_length=20, verbose_name='Индексувати та переходити по посиланням?')),
                ('object_id', models.PositiveIntegerField()),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name': 'Мета данні',
                'verbose_name_plural': 'Мета данні',
            },
        ),
    ]
