# Generated by Django 2.0.7 on 2018-07-16 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dseo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaticData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Назва')),
                ('slug', models.CharField(blank=True, max_length=255, verbose_name='Ссылка')),
                ('data', models.TextField(blank=True, max_length=2000, verbose_name='Данные')),
                ('file', models.FileField(blank=True, null=True, upload_to='files/%Y/%m/%d', verbose_name='Файл')),
            ],
            options={
                'verbose_name': 'Статична сторінка чи файл',
                'verbose_name_plural': 'Статичні сторінки чи файли',
            },
        ),
        migrations.AlterField(
            model_name='metadata',
            name='keywords',
            field=models.CharField(blank=True, max_length=255, verbose_name='Ключьові слова'),
        ),
    ]
