# Generated by Django 2.0.7 on 2018-07-16 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dseo', '0002_auto_20180716_1050'),
        ('dseo', '0002_auto_20180716_1030'),
    ]

    operations = [
    ]
