# Generated by Django 2.0.7 on 2018-07-18 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dseo', '0003_merge_20180716_1131'),
    ]

    operations = [
        migrations.AddField(
            model_name='counter',
            name='position',
            field=models.PositiveIntegerField(blank=True, choices=[(1, '<head>'), (2, '<body>')], default=0, help_text='для Google Analytics вибирати <head>, для більшості інших - <body>', verbose_name='Позиція'),
        ),
        migrations.AlterField(
            model_name='metadata',
            name='keywords',
            field=models.CharField(blank=True, max_length=255, verbose_name='Ключові слова'),
        ),
    ]
