
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-03-28T18:51:16+0000",
 "dirty": true,
 "error": null,
 "full-revisionid": "ee18726955dbc3b5fb9365dfca01e9b4a31b7e34",
 "version": "0.1.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
