# coding: utf-8

"""
    Nucleus API

    Nucleus text analytics APIs from SumUp Analytics. Example and documentation: https://github.com/SumUpAnalytics/nucleus-sdk  # noqa: E501

    OpenAPI spec version: v1.4.8
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from nucleus_api.models.nested_summary_model import NestedSummaryModel  # noqa: F401,E501


class NestedTopicSummaryModel(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'topic': 'str',
        'summary': 'list[NestedSummaryModel]'
    }

    attribute_map = {
        'topic': 'topic',
        'summary': 'summary'
    }

    def __init__(self, topic=None, summary=None):  # noqa: E501
        """NestedTopicSummaryModel - a model defined in Swagger"""  # noqa: E501

        self._topic = None
        self._summary = None
        self.discriminator = None

        if topic is not None:
            self.topic = topic
        if summary is not None:
            self.summary = summary

    @property
    def topic(self):
        """Gets the topic of this NestedTopicSummaryModel.  # noqa: E501

        Topic keywords  # noqa: E501

        :return: The topic of this NestedTopicSummaryModel.  # noqa: E501
        :rtype: str
        """
        return self._topic

    @topic.setter
    def topic(self, topic):
        """Sets the topic of this NestedTopicSummaryModel.

        Topic keywords  # noqa: E501

        :param topic: The topic of this NestedTopicSummaryModel.  # noqa: E501
        :type: str
        """

        self._topic = topic

    @property
    def summary(self):
        """Gets the summary of this NestedTopicSummaryModel.  # noqa: E501


        :return: The summary of this NestedTopicSummaryModel.  # noqa: E501
        :rtype: list[NestedSummaryModel]
        """
        return self._summary

    @summary.setter
    def summary(self, summary):
        """Sets the summary of this NestedTopicSummaryModel.


        :param summary: The summary of this NestedTopicSummaryModel.  # noqa: E501
        :type: list[NestedSummaryModel]
        """

        self._summary = summary

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(NestedTopicSummaryModel, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, NestedTopicSummaryModel):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
