# Generated by Django 2.1.7 on 2019-03-22 21:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LogRecord",
            fields=[
                ("created_at", models.DateTimeField(auto_created=True)),
                (
                    "uid",
                    models.UUIDField(
                        default=uuid.uuid4, primary_key=True, serialize=False
                    ),
                ),
                ("logger", models.CharField(max_length=255)),
                ("level", models.IntegerField()),
                ("trace", models.CharField(max_length=1024)),
                ("msg", models.CharField(max_length=1024)),
            ],
            options={"verbose_name": "LogRecord", "verbose_name_plural": "LogRecords"},
        )
    ]
