[tool.poetry]
name = "dlc-gui"
version = "0.6.1"
description = "Labeling GUI for DeepLabCut"
authors = ["d_ <UnicodeAlt255@gmail.com>"]
license = "LGPL-3.0+"
packages = [{include="dlc_gui", from="src"}]

[tool.poetry.dependencies]
python = "^3.6"
PySide2 = "=5.11.2"
"ruamel.yaml" = "^0.15"
numpy = "^1.0.0"
pandas = "^0.24.0"
tables = "^3.4"

[tool.poetry.dev-dependencies]
pytest = "^4.0.0"
pytest-qt = "^3.0.0"
hypothesis = "^4.0.0"
coverage = "^4.0.0"
pdbpp = "^0.9.5"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
