
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-04-08T17:25:47+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "03780724d2ca5133e066e4b9d9eaf9a744e4d6d2",
 "version": "0.10.5"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
