[tool.poetry]
name = "negmas"
version = "0.1.38"
description = "NEGotiations Managed by Agent Simulations"
authors = ["Yasser Mohammad <yasserfarouk@gmail.com>"]
license = "GPL-2.0+"

readme = 'README.rst'

repository = "https://github.com/yasserfarouk/negmas"
homepage = "https://github.com/yasserfarouk/negmas"

keywords = ['negotiation', 'mas', 'multi-agent', 'simulation', 'AI']

include = ["*.rst", "LICENSE"]
exclude = ["negmas/**/*.pyc", "nemgas/**/__pycache__", "config", "docs", "etc", "notebooks", "tests"]

[tool.poetry.dependencies]
python = ">=3.6"
Click = ">=6.0"
dataclasses = { version = "*", python = "<3.7" }
PyYAML = "5.1b1" # to avoid a security issue found by github
distributed = { version = "*", optional = true }
progressbar2 = ">=3.39"
typing_extensions = ">=3.7"
pytest-runner = ">=4.4"
pandas = ">=0.24.1"
scipy = ">=1.2"
numpy = ">=1.16"
stringcase = "*"
py4j = "*"
colorlog = "*"
inflect = "*"
matplotlib = "*"
setuptools = ">=40.8.0"
tabulate = "*"
typing = "*"
tqdm = ">=4.31.1"

[tool.poetry.dev-dependencies]
lockfile = "*"
pytest = "*"
pytest-cov = "*"
poetry = "*"
hypothesis = "*"
tox = "*"
poetry-setup = "*"
codacy-coverage = "*"
pytest-timeout = "^1.3"
coverage = "*"
bumpversion = "*"
typing-extensions = "*"
docopt =  { version = "*", optional = true }
docutils =  { version = "*", optional = true }
Sphinx =  { version = "*", optional = true }
sphinx-autodoc-annotation =  { version = "*", optional = true }
sphinx-autodoc-typehints =  { version = "*", optional = true }
sphinx-automodapi =  { version = "*", optional = true }
sphinx-rtd-theme =  { version = "*", optional = true }
sphinxcontrib-napoleon =  { version = "*", optional = true }
sphinxcontrib-websupport =  { version = "*", optional = true }
sphinxtesters =  { version = "*", optional = true }
ipykernel =  { version = "*", optional = true }
ipython =  { version = "*", optional = true }
ipython-genutils =  { version = "*", optional = true }
ipywidgets =  { version = "*", optional = true }
jupyter =  { version = "*", optional = true }
jupyter-client =  { version = "*", optional = true }
jupyter-console =  { version = "*", optional = true }
jupyter-contrib-core =  { version = "*", optional = true }
jupyter-contrib-nbextensions =  { version = "*", optional = true }
jupyter-core =  { version = "*", optional = true }
jupyter-highlight-selected-word =  { version = "*", optional = true }
jupyter-latex-envs =  { version = "*", optional = true }
jupyter-nbextensions-configurator =  { version = "*", optional = true }
MarkupSafe =  { version = "*", optional = true }
matplotlib =  { version = "*", optional = true }
nb2plots =  { version = "*", optional = true }
nbconvert =  { version = "*", optional = true }
nbformat =  { version = "*", optional = true }
nbsphinx =  { version = "*", optional = true }
pandoc =  { version = "*", optional = true }
pandocfilters =  { version = "*", optional = true }
pycodestyle =  { version = "*", optional = true }
pydocstyle =  { version = "*", optional = true }
readme-renderer =  { version = "*", optional = true }
recommonmark =  { version = "*", optional = true }


[tool.poetry.scripts]
negmas = 'negmas.scripts.app:cli'


[tool.poetry.extras]
dask = [
    "distributed"
]
doc = ["docopt", "docutils", "Sphinx", "sphinx-autodoc-annotation", "sphinx-autodoc-typehints", "sphinx-automodapi",
       "sphinx-rtd-theme", "sphinxcontrib-fulltoc", "sphinxcontrib-napoleon", "sphinxcontrib-websupport",
       "sphinxtesters", "ipykernel", "ipython", "ipython-genutils", "ipywidgets", "jupyter", "jupyter-client",
       "jupyter-console", "jupyter-contrib-core", "jupyter-contrib-nbextensions", "jupyter-core",
       "jupyter-highlight-selected-word", "jupyter-latex-envs", "jupyter-nbextensions-configurator",
       "MarkupSafe", "matplotlib", "nb2plots", "nbconvert", "nbformat", "nbsphinx", "pandoc",
       "pandocfilters", "pycodestyle", "pydocstyle", "readme-renderer", "recommonmark"
]


[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

