
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-03-29T16:57:48-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "58b5c9b1459c0818867abf7d2b590db0b42c6a4a",
 "version": "1.6.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
