group: travis_latest
language: python
git:
  depth: 1
python:
  - 2.7
  - 3.5
  - 3.6
  - pypy
  - pypy3
# As of Apr 2019, we can't use Python 3.7 at the top-level
# without using 'dist: xenial' at the top level. But that
# breaks PyPy and PyPy3 (they can't be installed)
matrix:
  include:
    - python: "3.7"
      dist: xenial

env:
  global:
    - PYTHONWARNINGS="ignore:'U' mode is deprecated:DeprecationWarning::"

before_install:
  - python --version

install:
  - pip install -U pip setuptools
  - pip install -U coverage coveralls pylint
  - pip install -U -e .[test]

script:
  - pylint -r no src/sphinxcontrib
  - coverage run setup.py test
after_success:
  - coveralls
notifications:
  email: false


cache: pip

before_cache:
    - rm -f $HOME/.cache/pip/log/debug.log
