
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-04-05T00:29:08-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "87f538da606635c93eaa4629a20a7873c3066d95",
 "version": "0.2.11"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
