# coding: utf-8

"""
    API

    API  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: you@your-company.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import telestream_cloud_stores
from telestream_cloud_stores.models.alternative_path_format import AlternativePathFormat  # noqa: E501
from telestream_cloud_stores.rest import ApiException


class TestAlternativePathFormat(unittest.TestCase):
    """AlternativePathFormat unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAlternativePathFormat(self):
        """Test AlternativePathFormat"""
        # FIXME: construct object with mandatory attributes with example values
        # model = telestream_cloud_stores.models.alternative_path_format.AlternativePathFormat()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
