# coding: utf-8

"""
    API

    API  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: you@your-company.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import telestream_cloud_stores
from telestream_cloud_stores.models.store_body_provider_specific_settings import StoreBodyProviderSpecificSettings  # noqa: E501
from telestream_cloud_stores.rest import ApiException


class TestStoreBodyProviderSpecificSettings(unittest.TestCase):
    """StoreBodyProviderSpecificSettings unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStoreBodyProviderSpecificSettings(self):
        """Test StoreBodyProviderSpecificSettings"""
        # FIXME: construct object with mandatory attributes with example values
        # model = telestream_cloud_stores.models.store_body_provider_specific_settings.StoreBodyProviderSpecificSettings()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
