
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-04-03T08:45:32-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "3f18721d8a6e9dbcd5e83945217cb660356ad820",
 "version": "0.5.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
