language: python
python:
    - "2.7"
    - "3.4"
branches:
    only:
        - master
virtualenv:
    system_site_packages: false
install:
    - pip install flake8
    - pip install python-coveralls
    - pip install coverage
    - pip install nose
    - pip install .
before_script:
    - flake8 --ignore E501,W504 contrail_api_cli
script:
    - nosetests --with-coverage
after_success:
    - coveralls
