# This file was automatically generated by sub\epyqlib\epyqlib\cli\generateversion.py
__version_build_time__ = '2019-04-07T00:35:18.584010'

__version__ = '2019.4.1'
__sha__ = '26633efbd6b099d1833535106bce011eb5d51ba6'
__revision__ = '26633efbd6b099d1833535106bce011eb5d51ba6'
