# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-31 03:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ubigeo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('reniec_code', models.CharField(max_length=6)),
                ('political_division', models.PositiveSmallIntegerField(choices=[(1, 'Region'), (2, 'Provincia'), (3, 'Distrito')])),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ubigeo.Ubigeo')),
            ],
        ),
    ]
