
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-04-04T12:01:35+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "59ec616348eabc9204ef3104a368e6a23c1fbf23",
 "version": "0.2.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
