
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "f6669526ec3470c8c0f4fc7f7c509858150dea1c",
 "version": "4.0.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
