# coding: utf-8

"""
    Nucleus API

    Nucleus text analytics APIs from SumUp Analytics. Example and documentation: https://github.com/SumUpAnalytics/nucleus-sdk  # noqa: E501

    OpenAPI spec version: v1.4.8
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import nucleus_api
from nucleus_api.models.nested_doc_rec_model import NestedDocRecModel  # noqa: E501
from nucleus_api.rest import ApiException


class TestNestedDocRecModel(unittest.TestCase):
    """NestedDocRecModel unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testNestedDocRecModel(self):
        """Test NestedDocRecModel"""
        # FIXME: construct object with mandatory attributes with example values
        # model = nucleus_api.models.nested_doc_rec_model.NestedDocRecModel()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
