- project:
    templates:
      - openstack-lower-constraints-jobs-neutron
      - openstack-python-jobs-neutron
      - publish-openstack-docs-pti
      - check-requirements
      - openstack-python35-jobs-neutron
      - openstack-python36-jobs-neutron
      - openstack-python37-jobs-neutron
      - release-notes-jobs-python3
