name: imagestats
channels:
    - defaults
dependencies:
    - "python>=3.5"
    - setuptools
    - "numpy>=1.13"
    - numpydoc
    - graphviz
    - pip:
      - sphinx
      - sphinx_rtd_theme
      - stsci_rtd_theme
      - sphinx_automodapi
