
# This file was generated by 'versioneer.py' (0.12) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

version_version = '0.8.1'
version_full = 'fd294e0ca5c79e6d6de751d1c21878e7d411e457'
def get_versions(default={}, verbose=False):
    return {'version': version_version, 'full': version_full}

