# coding: utf-8

"""
    Allegro REST API

    https://developer.allegro.pl/about  # noqa: E501

    OpenAPI spec version: latest
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import allegro_api
from allegro_api.models.price_modification_value_change import PriceModificationValueChange  # noqa: E501
from allegro_api.rest import ApiException


class TestPriceModificationValueChange(unittest.TestCase):
    """PriceModificationValueChange unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPriceModificationValueChange(self):
        """Test PriceModificationValueChange"""
        # FIXME: construct object with mandatory attributes with example values
        # model = allegro_api.models.price_modification_value_change.PriceModificationValueChange()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
