
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-03-28T15:50:33-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "20f5a2cb6e07787a56fc4f10a8c2fe444c6807a4",
 "version": "v0.6.6"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
