language: python
python:
  - "3.6"
install:
  pip install pycodestyle
script:
  - pycodestyle --show-source --show-pep8 --format=default spotifycli/spotifycli.py
  - pycodestyle --show-source --show-pep8 --format=default spotifycli/version.py
  - pycodestyle --show-source --show-pep8 --format=default spotifycli/__main__.py
  - pycodestyle --show-source --show-pep8 --format=default spotifycli/__init__.py
  - pycodestyle --show-source --show-pep8 --format=default setup.py
