# Generated by Django 2.1.5 on 2019-03-31 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saleboxdjango', '0005_auto_20190327_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='phone_1',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='phone_2',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='string_1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='string_2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
