# Generated by Django 2.1.4 on 2019-04-06 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saleboxdjango', '0006_auto_20190331_1517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkoutstore',
            name='code',
        ),
        migrations.RemoveField(
            model_name='checkoutstore',
            name='payment_method',
        ),
        migrations.AddField(
            model_name='checkoutstore',
            name='uuid',
            field=models.UUIDField(db_index=True, default='8468ee48-a709-434a-8fc8-ce516f809695'),
            preserve_default=False,
        ),
    ]
