
# This file was generated by 'versioneer.py' (0.16) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "7bd5e4e2a8bc085e1025f917f64fc2d7e1c687fe",
 "version": "1.0.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
