
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-03-27T15:21:07-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "506f6dd46c9e5d8a2bd79511efb0cd8fb15e9bc6",
 "version": "9.1.0b3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
