
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-04-04T08:28:47+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "8e811a0544b5182c4a72aed074b2ff8c4324e94d",
 "version": "1.5.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
