---
- name: upload admin ssh key
  hosts: localhost
  connection: local
  gather_facts: False

  pre_tasks:
    - include_vars: "{{ item }}"
      with_items:
        - ../../config/local/vars.yml
        - env.yml
      tags: always
  
  tasks:
    - ec2_key:
        name: "{{ aws_key_name }}"
        key_material: "{{ item }}"
      with_file: "../../config/private/{{ aws_key_name }}.pub"

- name:  set up vpn prerequisites
  hosts: localhost
  connection: local
  gather_facts: False

  pre_tasks:
    - include_vars: "{{ item }}"
      with_items:
        - ../../config/local/vars.yml
        - env.yml
      tags: always

  roles:
    - reactiveops.vpn-stack

- name: configure vpn instance
  hosts: tag_Layer_vpn_public_ip
  become: yes
  become_user: root

  pre_tasks:
    - include_vars: "{{ item }}"
      with_items:
        - ../../config/local/vars.yml
        - env.yml

  roles:
    - role: Stouts.openvpn-master
      vpn_role: 'primary'
      openvpn_first_run: "{{ hostvars['localhost']['openvpn_first_run'] }}"
