language: python
sudo: false
dist: xenial
services:
  - docker

cache:
  directories:
  - "${HOME}/.cache"
matrix:
  include:
  - python: 3.4
    env: TOXENV=py34
  - python: 3.5
    env: TOXENV=py35
  - python: 3.6
    env: TOXENV=py36
  - python: 3.7
    env: TOXENV=py37
install:
- pip install tox
script:
- tox
- docker run -v $(pwd)/policy:/opt/opa/policy openpolicyagent/opa test -v /opt/opa/policy
notifications:
  email: false
deploy:
  provider: pypi
  user: "cleardata"
  password:
    secure: "J7gFnr2nqonG5qCRskgzaQCSpyRK5Rp40pY0ANIi6tAr6duW9wEaB/MzDiE3TaHijyy1mf6aRAaSrP4FVuCUbIkIOGlMd7j09HNapkkt4anx6pD8ak8WaRlcuQuGNyvst+SwTxfDJMLUF5AeefLMx+H94+R6ToOgdIAVdXq/XNtJaY373GYXmRR5GMvfnJljqTgXsjBaLstzVYf5nlXAGMobJhphWapPzaFm0EjmN8sMQfMgxuHHGIjZ94B7x5GimGQo8sJxTYAEIFMBOKZ9oTSNghZLQTssbg0un5KWQkq1Enrs77durTZInyfgEGfDO/pHyYpLnRpRndnDaB/d0tl6tf/xXPVlU6krudCf1aijg8/6HstzVQfWacX65ZFALgy5MmurFL0bFqPsFK7iXgkpDbCNLSf4WKJqvbg/PF2L702/fELxE5huBnHX9q6n+agci6lZF/hCkFDcgFo8EZyoICyz3hI7ZrbJbTMsJ81gefQf7jrKlh6Fx/JthEdyxlrO/04V9Gq8btk34t/Ya8dAGaFT6/D9E7poeHoNvlnobVOj0XIL9pdU6lgu5bZcRpt51tSFe3z8b7GniST4r2OOjf3n+nYZa5LFwRP3zrTcvzjlRlejuo0CqxD2iomqzpNr/rBV6diuLlSl94q7Fsv8DcTVhphd20CdmduphMk="
  on:
    tags: true
  skip_existing: true
