
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-04-01T12:59:45-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "09d90bb6cf11d78ae0af01f3ef057cbf85d71dfc",
 "version": "0.1.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
