
# This file was generated by 'versioneer.py' (0.17) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-04-12T16:29:55-0500",
 "dirty": false,
 "error": null,
 "full-revisionid": "8c07c8783c777d3bb6615a0e7607f7f0e562b1d3",
 "version": "1.27.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
