sudo: false
language: python
dist: xenial

stages:
- test
- name: deploy
  if: repo = pytest-dev/pytest-subtests AND tag IS present

jobs:
  include:
    - python: '3.4'
      env: TOXENV=py34
    - python: '3.5'
      env: TOXENV=py35
    - python: '3.6'
      env: TOXENV=py36
    - python: '3.7'
      env: TOXENV=py37
    - python: 'pypy3.5-6.0'
      env: TOXENV=pypy3
    - python: '3.7'
      env: TOXENV=linting
    - stage: deploy
      python: '3.7'
      install: pip install -U setuptools setuptools_scm
      script: skip
      deploy:
        provider: pypi
        user: nicoddemus
        distributions: sdist bdist_wheel
        skip_upload_docs: true
        password:
          secure: CJBATZL5nzJNzjrvTRnMeJOKv1yFwSMp0jZ+GX4bDkq3+4H8EW08Hy/2DpCusK4fdC0CHT6CmO/YsLV9BuFdD4ozvBDhcuJqSLbPlt/R152xiOppvwZ9b2sMN6tmA8lIQB+nmwfmCIhI9jb9p882OZjz26C5ekD+RqM4JWpmh3KZqNLPsTR3xWOdL3WTET9HKNiWrwZtvJJwBKwF3ITE58SvHXMHfjCaWOk9hY2uK0+oUSev+Ww8L92jQLq73KLoSsEFvwKEKbssstcQmMk99jICvKaiOsQT0SarMzITWapQh9Thu2iRrfZVFr4AG3bywReeoM5zaXuwXOdEN1e+Lk2DRv0W/LQCDCWJiEBvDZXeIBT8B7aV8pHGKAw0P6xbkHOt2IE8tPZYcccqi6kV4b/Wz9Lqk4ilk/V4TYGAbss9wO2WORWAm1GQrg5zSAeivnmlB4sybwF6RGxJwC5Pr9KWYFPmKGQXdVsBmbiB4RpAsQfAdYIEWc9Kfn7aEQX6dthFEy9R6oWSlCY1aG0M4lLt/zOqKxr6pfdOqNwxgkMSeZkpmCU0jS5FPSJ8DuboAOdCU62MCV+6TM/CCFsrvYWxKgS2djO+9UGXiJjrWpWux2DlP6S8AuyADorExpZc+12VMLr6/+dqLRmo96yPcH6KH1owu2l/0ErAND/UF3A=
        on:
          tags: true
          repo: pytest-dev/pytest-subtests

install:
  - pip install --upgrade pip
  - pip install --upgrade setuptools tox

script:
  - tox

cache:
    directories:
        - $HOME/.cache/pre-commit
