# This file was auto-generated by ZETUP
#
# Zimmermann's Extensible Tools for Unified Project setups
#
# https://github.com/zimmermanncode/zetup


from __future__ import absolute_import

import sys
import os
from collections import OrderedDict

from zetup.version import Version
from zetup.dist import Distribution
from zetup.requires import Requirements
from zetup.extras import Extras
from zetup.package import Packages, Package
from zetup.notebook import Notebook



zfg = sys.modules[__name__]

NAME = 'zetup'

AUTHOR = 'Stefan Zimmermann'

KEYWORDS = ['zetup', 'project', 'tools', 'config', 'ini', 'setup', 'requirements', 'extras', 'packages', 'package', 'toplevel', 'object', 'meta', 'subprocess', 'process', 'popen', 'call', 'python3', 'python3']

MODULES = []

LICENSE = 'LGPLv3'

DISTRIBUTION = Distribution(zfg)

KEEP_MADE = []

SETUP_HOOKS = []

CLASSIFIERS = ['Development Status :: 3 - Alpha', 'Intended Audience :: Developers', 'License :: OSI Approved :: GNU Library or Lesser General Public License (LGPL)', 'Operating System :: OS Independent', 'Topic :: Software Development', 'Topic :: Utilities', 'Programming Language :: Python', 'Programming Language :: Python :: 2.7', 'Programming Language :: Python :: 3.4', 'Programming Language :: Python :: 3.5', 'Programming Language :: Python :: 3.6']

SETUP_KEYWORDS = {'use_zetup': 'zetup:setup_entry_point'}

NO_MAKE = ['setup.py', 'tox.ini']

EMAIL = 'user@zimmermann.co'

FORCE_MAKE = True

REQUIRES = Requirements("""
setuptools_scm >= 3.1

""", zfg=zfg)

in_repo = False

VERSION = Version('0.2.47')

TITLE = 'zetup'

SETUP_REQUIRES = None

URL = 'https://github.com/zimmermanncode/zetup'

DESCRIPTION = "Zimmermann's Extensible Tools for Unified Project_setups"

PACKAGES = Packages([

Package('zetup',
  sources=[
    'annotate.py',
    'classpackage.py',
    'conda.py',
    'config.py',
    'dist.py',
    'error.py',
    'extras.py',
    'func.py',
    'modules.py',
    'object.py',
    'package.py',
    'requires.py',
    'resolve.py',
    'script.py',
    'test_classpackage.py',
    'version.py',
    'zetup.py',
    'zetup_config.py',
    '__init__.py',
    '__main__.py'
    ],
  subpackages=[
    
Package('zetup.commands',
  sources=[
    'command.py',
    'conda.py',
    'del_.py',
    'dev.py',
    'error.py',
    'pytest.py',
    'run.py',
    'test.py',
    'tox.py',
    '__init__.py'
    ],
  subpackages=[
    
Package('zetup.commands.make',
  sources=[
    '__init__.py'
    ],
  subpackages=[
    
    ],
  )

    ],
  )
,
    
Package('zetup.doc',
  sources=[
    '__init__.py'
    ],
  subpackages=[
    
    ],
  )
,
    
Package('zetup.notebook',
  sources=[
    'jinja.py',
    '__init__.py'
    ],
  subpackages=[
    
    ],
  )
,
    
Package('zetup.pip',
  sources=[
    'errors.py',
    'test_errors.py',
    '__init__.py'
    ],
  subpackages=[
    
    ],
  )
,
    
Package('zetup.process',
  sources=[
    'scons.py',
    '__init__.py'
    ],
  subpackages=[
    
    ],
  )

    ],
  )

  ], root=os.path.dirname(os.path.dirname(os.path.realpath(__file__))))

TEST_COMMANDS = ['py.test -v test']

PYTHON = ['2.7', '3.4', '3.5', '3.6']

SCRIPTS = {'zetup': 'zetup.script:run'}

EXTRAS = Extras([
('commands', Requirements("""
path.py >= 11.5 #import path
jinjatools >= 0.1.7

""")),
('notebook', Requirements("""
path.py >= 11.5 #import path
nbconvert >= 5.4

""")),
('pytest', Requirements("""
pytest >= 4.3

"""))
], zfg=zfg)