[tool.poetry]
name = "la-businesses"
version = "0.1.0"
description = ""
authors = ["Manuel Ochoa <dev@manuelochoa.com>"]

[tool.poetry.dependencies]
python = "^3.7"
requests = "^2.21"
pandas = "^0.24.2"
simplekml = "^1.3"
pytz = "^2018.9"

[tool.poetry.dev-dependencies]
pytest = "^3.0"

[tool.poetry.scripts]
la-businesses = "la_businesses:main"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

