# Default YAML configuration script for Eniric.

# Paths to locations used by eniric, relative to config.yaml.
# Paths can either be strings of list of strings which will be passed
# to :py:func:`os.path.join` (This is for os independence)
paths:
  phoenix_raw: ["..", "data", "phoenix-raw"] # Path to Phoenix-ACES spectra
  btsettl_raw: ["..", "data", "btsettl-raw"] # Path to BT-Settl spectra
  atmmodel: ["..", "data", "atmmodel"] # Path of atmosphere model directory
  precision_results: ["..", "data", "precision"]  # A place to put precision results

# Wavelength bands.
bands:
  all: ["VIS", "GAP", "Z", "Y", "J", "H", "K", "CONT", "NIR", "TEST"] # "all" name available in scripts
# Already included wavelength bands  (see `eniric.utilities.py`)
# "VIS": (0.38, 0.78),
# "GAP": (0.78, 0.83),
# "Z": (0.83, 0.93),
# "Y": (1.0, 1.1),
# "J": (1.17, 1.33),
# "H": (1.5, 1.75),
# "K": (2.07, 2.35),
# "CONT": (0.45, 1.05),
# "NIR": (0.83, 2.35)

# Add your custom band limits here and include in "all" list above.
# Limits must be contained in lists.
custom_bands:
  TEST: [2.1, 2.2]

# Location of the joblib memory cache.
cache:
  # location: None  # Disables cache
  location: [".joblib"]

# Properties of the atmospheric model used.
atmmodel:
  # Base name of telluric model
  base: "Average_TAPAS_2014"

# Necessary configuration keywords for Starfish can be included in this file.
name: "default"
