
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-03-28T22:19:24+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "5e0f8af60bafe6b5c79126d455f416904cdeadf0",
 "version": "0.12.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
