- project:
    check:
      jobs:
        - networking-l2gw-tempest-dummy
        - l2gw-tox-lower-constraints
    gate:
      jobs:
        - networking-l2gw-tempest-dummy
        - l2gw-tox-lower-constraints

- job:
    name: l2gw-tox-lower-constraints
    parent: openstack-tox-lower-constraints
    required-projects:
      - openstack/neutron
