
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-03-27T09:33:52+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "dfff3c965fea83c0429b17c37a0668b6023f519b",
 "version": "0.26.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
