[tool.poetry]
name = "synapse-p2p"
version = "0.1.1"
description = "A rapid RPC framework for building p2p networks"
authors = ["Daniel van Flymen <vanflymen@gmail.com>"]
homepage = "https://github.com/dvf/synapse"

[tool.poetry.dependencies]
python = "^3.7"
loguru = "*"
msgpack = "*"

[tool.poetry.dev-dependencies]
faker = "*"
pytest = "*"
pytest-sugar = "*"
pytest-cov = "*"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
