
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-04-01T10:58:03+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "7f4d4a8946d3dc62f990a974c7110e5763bf83a4",
 "version": "1.8.25"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
