# Generated by Django 2.1.4 on 2019-04-06 04:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saleboxdjango', '0007_auto_20190406_1153'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkoutstore',
            old_name='visible_code',
            new_name='visible_id',
        ),
    ]
