
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-04-03T15:26:28+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "38b6142bd52937a8f790b5f2403080fc5cc8b7fe",
 "version": "1.16.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
