# coding: utf-8

# flake8: noqa
"""
    API

    API  # noqa: E501

    OpenAPI spec version: 1.0.0
    Contact: you@your-company.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import models into model package
from telestream_cloud_stores.models.alternative_path_format import AlternativePathFormat
from telestream_cloud_stores.models.error import Error
from telestream_cloud_stores.models.error_response import ErrorResponse
from telestream_cloud_stores.models.object_url import ObjectURL
from telestream_cloud_stores.models.output import Output
from telestream_cloud_stores.models.store import Store
from telestream_cloud_stores.models.store_body import StoreBody
from telestream_cloud_stores.models.store_body_provider_specific_settings import StoreBodyProviderSpecificSettings
from telestream_cloud_stores.models.validate_bucket_body import ValidateBucketBody
from telestream_cloud_stores.models.validate_bucket_response import ValidateBucketResponse
from telestream_cloud_stores.models.watch_rule import WatchRule
