
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "d5bb4be133cd9c53d2a9041da42b6541ee09aa43",
 "version": "0.15.0.b3828"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
