# coding: utf-8

"""
    Allegro REST API

    https://developer.allegro.pl/about  # noqa: E501

    OpenAPI spec version: latest
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import allegro_api
from allegro_api.api.products_api import ProductsApi  # noqa: E501
from allegro_api.rest import ApiException


class TestProductsApi(unittest.TestCase):
    """ProductsApi unit test stubs"""

    def setUp(self):
        self.api = allegro_api.api.products_api.ProductsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_get_sale_product(self):
        """Test case for get_sale_product

        Get all data of the particular product  # noqa: E501
        """
        pass

    def test_get_sale_products(self):
        """Test case for get_sale_products

        Get search products results  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
