
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-04-05T12:37:54-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "a54846135ba7c0d9e6e65ebf6a0bf16830d6b2f2",
 "version": "2019.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
