
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-04-10T14:36:48-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "90693f2d661f75e92fdebb4dedbdeaf755dfe0a1",
 "version": "v0.2.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
