
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "94d75b9e6bea3840bc39a658a4eb4e1e7be42453",
 "version": "2124"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
