# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_pid_tune_methods_main_window.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(670, 235)
        MainWindow.setMinimumSize(QtCore.QSize(670, 235))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/img/Calculator-32.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtGui.QWidget(MainWindow)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setMinimumSize(QtCore.QSize(0, 0))
        self.centralwidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.gbTuneMethod = QtGui.QGroupBox(self.centralwidget)
        self.gbTuneMethod.setMinimumSize(QtCore.QSize(280, 0))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.gbTuneMethod.setFont(font)
        self.gbTuneMethod.setObjectName(_fromUtf8("gbTuneMethod"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.gbTuneMethod)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.gridLayoutPIDMethod = QtGui.QGridLayout()
        self.gridLayoutPIDMethod.setObjectName(_fromUtf8("gridLayoutPIDMethod"))
        self.cmbTuneMethod = QtGui.QComboBox(self.gbTuneMethod)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.cmbTuneMethod.setFont(font)
        self.cmbTuneMethod.setObjectName(_fromUtf8("cmbTuneMethod"))
        self.gridLayoutPIDMethod.addWidget(self.cmbTuneMethod, 1, 1, 1, 1)
        self.cmbPIDType = QtGui.QComboBox(self.gbTuneMethod)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.cmbPIDType.setFont(font)
        self.cmbPIDType.setObjectName(_fromUtf8("cmbPIDType"))
        self.gridLayoutPIDMethod.addWidget(self.cmbPIDType, 2, 1, 1, 1)
        self.lblTuneMethod = QtGui.QLabel(self.gbTuneMethod)
        self.lblTuneMethod.setMinimumSize(QtCore.QSize(105, 0))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblTuneMethod.setFont(font)
        self.lblTuneMethod.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblTuneMethod.setObjectName(_fromUtf8("lblTuneMethod"))
        self.gridLayoutPIDMethod.addWidget(self.lblTuneMethod, 1, 0, 1, 1)
        self.lblPIDType = QtGui.QLabel(self.gbTuneMethod)
        self.lblPIDType.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblPIDType.setFont(font)
        self.lblPIDType.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblPIDType.setObjectName(_fromUtf8("lblPIDType"))
        self.gridLayoutPIDMethod.addWidget(self.lblPIDType, 2, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(100, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayoutPIDMethod.addItem(spacerItem, 1, 2, 1, 1)
        self.lblLambdaTauRatio = QtGui.QLabel(self.gbTuneMethod)
        self.lblLambdaTauRatio.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblLambdaTauRatio.setFont(font)
        self.lblLambdaTauRatio.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblLambdaTauRatio.setObjectName(_fromUtf8("lblLambdaTauRatio"))
        self.gridLayoutPIDMethod.addWidget(self.lblLambdaTauRatio, 3, 0, 1, 1)
        self.leLambdaTauRatio = QtGui.QLineEdit(self.gbTuneMethod)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.leLambdaTauRatio.setFont(font)
        self.leLambdaTauRatio.setInputMask(_fromUtf8(""))
        self.leLambdaTauRatio.setReadOnly(True)
        self.leLambdaTauRatio.setObjectName(_fromUtf8("leLambdaTauRatio"))
        self.gridLayoutPIDMethod.addWidget(self.leLambdaTauRatio, 3, 1, 1, 1)
        self.lblLambda = QtGui.QLabel(self.gbTuneMethod)
        self.lblLambda.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblLambda.setFont(font)
        self.lblLambda.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblLambda.setObjectName(_fromUtf8("lblLambda"))
        self.gridLayoutPIDMethod.addWidget(self.lblLambda, 4, 0, 1, 1)
        self.leLambda = QtGui.QLineEdit(self.gbTuneMethod)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.leLambda.setFont(font)
        self.leLambda.setReadOnly(False)
        self.leLambda.setObjectName(_fromUtf8("leLambda"))
        self.gridLayoutPIDMethod.addWidget(self.leLambda, 4, 1, 1, 1)
        self.lblProccess = QtGui.QLabel(self.gbTuneMethod)
        self.lblProccess.setMinimumSize(QtCore.QSize(105, 0))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblProccess.setFont(font)
        self.lblProccess.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblProccess.setObjectName(_fromUtf8("lblProccess"))
        self.gridLayoutPIDMethod.addWidget(self.lblProccess, 0, 0, 1, 1)
        self.cmbProccess = QtGui.QComboBox(self.gbTuneMethod)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.cmbProccess.setFont(font)
        self.cmbProccess.setObjectName(_fromUtf8("cmbProccess"))
        self.gridLayoutPIDMethod.addWidget(self.cmbProccess, 0, 1, 1, 1)
        self.verticalLayout_4.addLayout(self.gridLayoutPIDMethod)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem1)
        self.gridLayout.addWidget(self.gbTuneMethod, 0, 1, 1, 1)
        self.gbProcess = QtGui.QGroupBox(self.centralwidget)
        self.gbProcess.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.gbProcess.setFont(font)
        self.gbProcess.setObjectName(_fromUtf8("gbProcess"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.gbProcess)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.gridLayoutProccess = QtGui.QGridLayout()
        self.gridLayoutProccess.setObjectName(_fromUtf8("gridLayoutProccess"))
        self.lblGain = QtGui.QLabel(self.gbProcess)
        self.lblGain.setMinimumSize(QtCore.QSize(105, 0))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblGain.setFont(font)
        self.lblGain.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblGain.setObjectName(_fromUtf8("lblGain"))
        self.gridLayoutProccess.addWidget(self.lblGain, 0, 0, 1, 1)
        self.leTc = QtGui.QLineEdit(self.gbProcess)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.leTc.setFont(font)
        self.leTc.setObjectName(_fromUtf8("leTc"))
        self.gridLayoutProccess.addWidget(self.leTc, 1, 1, 1, 1)
        self.leGain = QtGui.QLineEdit(self.gbProcess)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.leGain.setFont(font)
        self.leGain.setObjectName(_fromUtf8("leGain"))
        self.gridLayoutProccess.addWidget(self.leGain, 0, 1, 1, 1)
        self.lblTc = QtGui.QLabel(self.gbProcess)
        self.lblTc.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblTc.setFont(font)
        self.lblTc.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblTc.setObjectName(_fromUtf8("lblTc"))
        self.gridLayoutProccess.addWidget(self.lblTc, 1, 0, 1, 1)
        self.lblDeadTime = QtGui.QLabel(self.gbProcess)
        self.lblDeadTime.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblDeadTime.setFont(font)
        self.lblDeadTime.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblDeadTime.setObjectName(_fromUtf8("lblDeadTime"))
        self.gridLayoutProccess.addWidget(self.lblDeadTime, 2, 0, 1, 1)
        self.leDeadTime = QtGui.QLineEdit(self.gbProcess)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.leDeadTime.setFont(font)
        self.leDeadTime.setObjectName(_fromUtf8("leDeadTime"))
        self.gridLayoutProccess.addWidget(self.leDeadTime, 2, 1, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(100, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayoutProccess.addItem(spacerItem2, 0, 2, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayoutProccess)
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem3)
        self.gridLayout.addWidget(self.gbProcess, 0, 0, 1, 1)
        self.gbPIDParams = QtGui.QGroupBox(self.centralwidget)
        self.gbPIDParams.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.gbPIDParams.setFont(font)
        self.gbPIDParams.setObjectName(_fromUtf8("gbPIDParams"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.gbPIDParams)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.gridLayoutPIDParams = QtGui.QGridLayout()
        self.gridLayoutPIDParams.setObjectName(_fromUtf8("gridLayoutPIDParams"))
        self.leTd = QtGui.QLineEdit(self.gbPIDParams)
        self.leTd.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leTd.sizePolicy().hasHeightForWidth())
        self.leTd.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.leTd.setFont(font)
        self.leTd.setReadOnly(True)
        self.leTd.setObjectName(_fromUtf8("leTd"))
        self.gridLayoutPIDParams.addWidget(self.leTd, 2, 1, 1, 1)
        self.lblTd = QtGui.QLabel(self.gbPIDParams)
        self.lblTd.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblTd.setFont(font)
        self.lblTd.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblTd.setObjectName(_fromUtf8("lblTd"))
        self.gridLayoutPIDParams.addWidget(self.lblTd, 2, 0, 1, 1)
        self.lblKc = QtGui.QLabel(self.gbPIDParams)
        self.lblKc.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblKc.setFont(font)
        self.lblKc.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblKc.setObjectName(_fromUtf8("lblKc"))
        self.gridLayoutPIDParams.addWidget(self.lblKc, 0, 0, 1, 1)
        self.leKc = QtGui.QLineEdit(self.gbPIDParams)
        self.leKc.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leKc.sizePolicy().hasHeightForWidth())
        self.leKc.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.leKc.setFont(font)
        self.leKc.setReadOnly(True)
        self.leKc.setObjectName(_fromUtf8("leKc"))
        self.gridLayoutPIDParams.addWidget(self.leKc, 0, 1, 1, 1)
        self.lblTi = QtGui.QLabel(self.gbPIDParams)
        self.lblTi.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.lblTi.setFont(font)
        self.lblTi.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lblTi.setObjectName(_fromUtf8("lblTi"))
        self.gridLayoutPIDParams.addWidget(self.lblTi, 1, 0, 1, 1)
        self.leTi = QtGui.QLineEdit(self.gbPIDParams)
        self.leTi.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leTi.sizePolicy().hasHeightForWidth())
        self.leTi.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.leTi.setFont(font)
        self.leTi.setReadOnly(True)
        self.leTi.setObjectName(_fromUtf8("leTi"))
        self.gridLayoutPIDParams.addWidget(self.leTi, 1, 1, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(100, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayoutPIDParams.addItem(spacerItem4, 0, 2, 1, 1)
        spacerItem5 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayoutPIDParams.addItem(spacerItem5, 3, 1, 1, 1)
        self.verticalLayout_2.addLayout(self.gridLayoutPIDParams)
        self.gridLayout.addWidget(self.gbPIDParams, 0, 2, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 670, 18))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        self.menuPlots = QtGui.QMenu(self.menubar)
        self.menuPlots.setObjectName(_fromUtf8("menuPlots"))
        self.menuProccess = QtGui.QMenu(self.menuPlots)
        self.menuProccess.setObjectName(_fromUtf8("menuProccess"))
        self.menuClosedLoop = QtGui.QMenu(self.menuPlots)
        self.menuClosedLoop.setObjectName(_fromUtf8("menuClosedLoop"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.mainToolBar = QtGui.QToolBar(MainWindow)
        self.mainToolBar.setObjectName(_fromUtf8("mainToolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.actionRefresh = QtGui.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/img/cyclic-process-16.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRefresh.setIcon(icon1)
        self.actionRefresh.setObjectName(_fromUtf8("actionRefresh"))
        self.actionExit = QtGui.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/img/exit-16.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExit.setIcon(icon2)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.actionAbout = QtGui.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/img/info-sign-16.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAbout.setIcon(icon3)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.actionHelp = QtGui.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/img/help-desk-icon-16.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionHelp.setIcon(icon4)
        self.actionHelp.setObjectName(_fromUtf8("actionHelp"))
        self.action_P_Step_Impulse_Response = QtGui.QAction(MainWindow)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/img/line-graph-16.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_P_Step_Impulse_Response.setIcon(icon5)
        self.action_P_Step_Impulse_Response.setObjectName(_fromUtf8("action_P_Step_Impulse_Response"))
        self.action_CL_Step_Impulse_Response = QtGui.QAction(MainWindow)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/img/diagramm-16.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_CL_Step_Impulse_Response.setIcon(icon6)
        self.action_CL_Step_Impulse_Response.setObjectName(_fromUtf8("action_CL_Step_Impulse_Response"))
        self.action_P_Bode_Response = QtGui.QAction(MainWindow)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/img/barchart-col-16.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_P_Bode_Response.setIcon(icon7)
        self.action_P_Bode_Response.setObjectName(_fromUtf8("action_P_Bode_Response"))
        self.action_CL_Bode_Response = QtGui.QAction(MainWindow)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/img/barchart-bw-16.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.action_CL_Bode_Response.setIcon(icon8)
        self.action_CL_Bode_Response.setObjectName(_fromUtf8("action_CL_Bode_Response"))
        self.menuFile.addAction(self.actionRefresh)
        self.menuFile.addSeparator()
        self.menuFile.addAction(self.actionExit)
        self.menuHelp.addAction(self.actionHelp)
        self.menuHelp.addAction(self.actionAbout)
        self.menuProccess.addAction(self.action_P_Step_Impulse_Response)
        self.menuProccess.addAction(self.action_P_Bode_Response)
        self.menuClosedLoop.addAction(self.action_CL_Step_Impulse_Response)
        self.menuClosedLoop.addAction(self.action_CL_Bode_Response)
        self.menuPlots.addAction(self.menuProccess.menuAction())
        self.menuPlots.addAction(self.menuClosedLoop.menuAction())
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuPlots.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.lblTuneMethod.setBuddy(self.cmbTuneMethod)
        self.lblPIDType.setBuddy(self.cmbPIDType)
        self.lblLambdaTauRatio.setBuddy(self.leLambdaTauRatio)
        self.lblLambda.setBuddy(self.leLambda)
        self.lblProccess.setBuddy(self.cmbProccess)
        self.lblGain.setBuddy(self.leGain)
        self.lblTc.setBuddy(self.leTc)
        self.lblDeadTime.setBuddy(self.leDeadTime)
        self.lblTd.setBuddy(self.leTd)
        self.lblKc.setBuddy(self.leKc)
        self.lblTi.setBuddy(self.leTi)

        self.retranslateUi(MainWindow)
        self.cmbTuneMethod.setCurrentIndex(-1)
        self.cmbProccess.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.leGain, self.leTc)
        MainWindow.setTabOrder(self.leTc, self.leDeadTime)
        MainWindow.setTabOrder(self.leDeadTime, self.cmbProccess)
        MainWindow.setTabOrder(self.cmbProccess, self.cmbTuneMethod)
        MainWindow.setTabOrder(self.cmbTuneMethod, self.cmbPIDType)
        MainWindow.setTabOrder(self.cmbPIDType, self.leLambdaTauRatio)
        MainWindow.setTabOrder(self.leLambdaTauRatio, self.leLambda)
        MainWindow.setTabOrder(self.leLambda, self.leKc)
        MainWindow.setTabOrder(self.leKc, self.leTi)
        MainWindow.setTabOrder(self.leTi, self.leTd)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "PID Tune Methods", None))
        self.gbTuneMethod.setTitle(_translate("MainWindow", "2 > Tune Method", None))
        self.cmbTuneMethod.setToolTip(_translate("MainWindow", "PID method", None))
        self.cmbPIDType.setToolTip(_translate("MainWindow", "P or PI or PID controller type", None))
        self.lblTuneMethod.setText(_translate("MainWindow", "Method", None))
        self.lblPIDType.setText(_translate("MainWindow", "Type", None))
        self.lblLambdaTauRatio.setText(_translate("MainWindow", "Tau Ratio", None))
        self.leLambdaTauRatio.setToolTip(_translate("MainWindow", "closed loop tc / process tc", None))
        self.lblLambda.setText(_translate("MainWindow", "Lambda Value [s]", None))
        self.leLambda.setToolTip(_translate("MainWindow", "closed loop tc", None))
        self.leLambda.setInputMask(_translate("MainWindow", "99.99;_", None))
        self.leLambda.setText(_translate("MainWindow", "00.00", None))
        self.lblProccess.setText(_translate("MainWindow", "Proccess", None))
        self.cmbProccess.setToolTip(_translate("MainWindow", "First order with dead time or integrating", None))
        self.gbProcess.setTitle(_translate("MainWindow", "1 > Process", None))
        self.lblGain.setText(_translate("MainWindow", "Gain", None))
        self.leTc.setToolTip(_translate("MainWindow", "Process time constant", None))
        self.leTc.setInputMask(_translate("MainWindow", "99.99;_", None))
        self.leTc.setText(_translate("MainWindow", "00.00", None))
        self.leGain.setToolTip(_translate("MainWindow", "Proccess gain", None))
        self.leGain.setInputMask(_translate("MainWindow", "99.99;_", None))
        self.leGain.setText(_translate("MainWindow", "00.00", None))
        self.lblTc.setText(_translate("MainWindow", "Time Constant [s]", None))
        self.lblDeadTime.setText(_translate("MainWindow", "Dead time [s]", None))
        self.leDeadTime.setToolTip(_translate("MainWindow", "Process dead time", None))
        self.leDeadTime.setInputMask(_translate("MainWindow", "99.99;_", None))
        self.leDeadTime.setText(_translate("MainWindow", "00.00", None))
        self.gbPIDParams.setTitle(_translate("MainWindow", "3 > PID Params", None))
        self.leTd.setToolTip(_translate("MainWindow", "Controller derivative time", None))
        self.lblTd.setText(_translate("MainWindow", "Td", None))
        self.lblKc.setText(_translate("MainWindow", "Kc", None))
        self.leKc.setToolTip(_translate("MainWindow", "Controller gain", None))
        self.lblTi.setText(_translate("MainWindow", "Ti", None))
        self.leTi.setToolTip(_translate("MainWindow", "Controller integral time", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.menuHelp.setTitle(_translate("MainWindow", "Help", None))
        self.menuPlots.setTitle(_translate("MainWindow", "Plots", None))
        self.menuProccess.setTitle(_translate("MainWindow", "Proccess", None))
        self.menuClosedLoop.setTitle(_translate("MainWindow", "Closed Loop", None))
        self.mainToolBar.setWindowTitle(_translate("MainWindow", "toolBar", None))
        self.actionRefresh.setText(_translate("MainWindow", "Refresh", None))
        self.actionExit.setText(_translate("MainWindow", "Exit", None))
        self.actionAbout.setText(_translate("MainWindow", "About...", None))
        self.actionHelp.setText(_translate("MainWindow", "Help", None))
        self.action_P_Step_Impulse_Response.setText(_translate("MainWindow", "Step/Impulse Plot", None))
        self.action_P_Step_Impulse_Response.setToolTip(_translate("MainWindow", "Proccess Step/Impulse Plot", None))
        self.action_CL_Step_Impulse_Response.setText(_translate("MainWindow", "Step/Impulse Plot", None))
        self.action_CL_Step_Impulse_Response.setToolTip(_translate("MainWindow", "Closed Loop Step/Impulse Plot", None))
        self.action_P_Bode_Response.setText(_translate("MainWindow", "Bode Plot", None))
        self.action_P_Bode_Response.setToolTip(_translate("MainWindow", "Proccess Bode Plot", None))
        self.action_CL_Bode_Response.setText(_translate("MainWindow", "Bode Plot", None))
        self.action_CL_Bode_Response.setToolTip(_translate("MainWindow", "Closed Loop Bode Plot", None))

import PIDTuneMethods_rc
