
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-04-01T00:50:06+0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "891ab0779bdb6ceeac2711143b01d2222f41c4b0",
 "version": "0.8.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
