# This file was automatically generated by sub\epyqlib\epyqlib\cli\generateversion.py
__version_build_time__ = '2019-03-28T19:19:59.770841'

__version__ = '2019.3.6'
__sha__ = 'dc5021aae04cbfea971fc77c205d72e666c612be'
__revision__ = 'dc5021aae04cbfea971fc77c205d72e666c612be'
