
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-04-09T12:58:10-0600",
 "dirty": false,
 "error": null,
 "full-revisionid": "504b4f14121a74ae7bd6e6038f0c5b8300046808",
 "version": "0.4.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
