# coding: utf-8

"""
    Allegro REST API

    https://developer.allegro.pl/about  # noqa: E501

    OpenAPI spec version: latest
    Generated by: https://openapi-generator.tech
"""


from setuptools import setup, find_packages  # noqa: H301

NAME = "allegro-pl-rest-api"
VERSION = "2019.4"
# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools

REQUIRES = ["urllib3 >= 1.15", "six >= 1.10", "certifi", "python-dateutil"]

setup(
    name=NAME,
    version=VERSION,
    description="Allegro REST API client",
    author_email="",
    url="https://github.com/mattesilver/allegro-pl-rest-api",
    keywords=["OpenAPI", "OpenAPI-Generator", "Allegro REST API client"],
    install_requires=REQUIRES,
    packages=find_packages(),
    include_package_data=True,
    long_description="""\
    https://developer.allegro.pl/about  # noqa: E501
    """
)
