[tool.poetry]
name = "confdict"
version = "0.0.1"
description = "A dictionary with nested access, interpolation and fallback features. It is primarily meant to be used for storing configurations of programs."
authors = [
  "Mehmet Can Ozdemir <mefu.ozd@gmail.com>"
]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.4"

[tool.poetry.dev-dependencies]
pytest = "^4.1"
pytest-cov = "^2.5"
coverage = "^4.5.3"
yapf = "^0.26.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
