[tool.poetry]
name = "pytel-inject"
version = "0.1.0"
description = ""
authors = ["Rafal Krupinski"]
packages = [{include = 'pytel', from = 'src'}]
license = "Apache-2.0"

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]
pytest = "^3.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
