
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-04-05T17:54:07-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "dbeee9a433d3d2202407f2e4ff8a0be96a8dca89",
 "version": "0.4.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
