[tool.poetry]
name = "main_script"
version = "0.1.0"
description = "A simple decorator to replace if __name__ == '__main__' with @main_script"
authors = ["Matt Kramer <matthew.robert.kramer@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.7"

[tool.poetry.dev-dependencies]
pytest = "^4.3"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
