[tool.poetry]
name = "gcal2redmine"
version = "0.1.0"
description = "Fill Redmine's time tracker from a Google Calendar"
authors = ["Nicolas KAROLAK <nicolas@karolak.fr>"]
license = "WTFPL"
classifiers = [
    "Development Status :: 4 - Beta",
    "Environment :: Console",
    "Operating System :: POSIX :: Linux",
    "Topic :: Office/Business :: Scheduling",
    "Topic :: Software Development :: Bug Tracking",
]
keywords = [
    "redmine",
    "google calendar",
    "time tracking",
]

[tool.poetry.dependencies]
python = "^3.6"
google-api-python-client = "^1.7"
python-redmine = "^2.1"
oauth2client = "^4.1"
click = "^7.0"
tzlocal = "^1.5"

[tool.poetry.dev-dependencies]
pylint = "^2.3"
black = {version = "*", allows-prereleases = true}
mypy = "^0.670.0"
ipython = "^7.4"

[tool.poetry.scripts]
gcal2redmine = 'gcal2redmine.cli:main'

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
