[tool.poetry]
name = "publish_sphinx_docs"
version = "1.0.1"
description = "A simple Python 3.6+ CLI to publish your Sphinx documentation to a Github Pages or Gitlab Pages repository."
authors = ["Alex Raichev <araichev@mrcagney.com>"]
readme = "README.rst"
license = "MIT"

[tool.poetry.dependencies]
python = "^3.6"
ghp-import = "^0.5.5"
click = "^7.0"

[tool.poetry.dev-dependencies]
pytest = "^3.0"
sphinx-click = "^2.0"

[tool.poetry.scripts]
publish-sphinx-docs = 'publish_sphinx_docs:main.publish'

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
