
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-03-30T17:40:25-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "ea9e4017049f25337903651db288dcd89750963f",
 "version": "v0.1.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
