
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "bdb6b419625f7db11e21b6872e279a0856ff83d2",
 "version": "2120"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
