
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2019-03-29T19:15:57-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "f3d39fe7ff7d860b1c6a2dfd7141e1647106d93d",
 "version": "v0.6.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
